import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
import { SCIENCE_WORDS } from "@/lib/partners/product-guides";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
export const metadata=withSocialMetadata({title:"BAC Water Glossary: Mass, Volume, Concentration and Label Terms",description:"Understand BAC water, benzyl alcohol, reconstitution, concentration, U-100 scale and related label terms. Definitions are not preparation or treatment instructions.",alternates:{canonical:"/learn/glossary"}});
const terms=[
 ...SCIENCE_WORDS.map(([name,text],i)=>({id:`research-word-${i}`,name,text,href:"/research-finder",link:"Explore a research question"})),
 {id:"ml",name:"Milliliter (mL)",text:"A unit for how much liquid there is. A liter holds 1,000 mL. To find how many mg are in that liquid, you also need to know the amount in each mL.",href:"/tools/syringe-units",link:"Convert U-100 volume units"},
 {id:"bacteriostatic-water",name:"Bacteriostatic water",text:"Water with an added chemical that slows the growth of bacteria. The exact label tells you what is in it. The name does not prove it can be mixed with another product.",href:"/learn/what-is-bac-water",link:"Ingredients and labeled purpose"},
 {id:"benzyl-alcohol",name:"Benzyl alcohol",text:"A chemical added to some water products to slow the growth of bacteria. Check how much is listed on the label. It does not remove all germs or prove that a later mixture is free of them.",href:"/learn/vs/benzyl-alcohol",link:"Ingredient versus finished product"},
 {id:"bacteriostatic",name:"Bacteriostatic",text:"Slows the growth of bacteria. It does not mean all germs have been removed or that no germs can enter later.",href:"/learn/what-you-cannot-know",link:"Limits of a product label and calculator"},
 {id:"reconstitution",name:"Reconstitution",text:"Adding the liquid named in the instructions to a dry product that needs it. The product instructions must name the liquid and the final amount of liquid. A calculator cannot choose them.",href:"/learn/how-peptide-reconstitution-works",link:"Reconstitution and concentration are different questions"},
 {id:"lyophilization",name:"Lyophilization",text:"Freeze-drying: freezing a material, then removing water to leave it dry. The powder still needs its own storage and handling instructions. The word does not tell you how long it lasts.",href:"/learn/how-to-read-a-peptide-vial",link:"Interpreting label information"},
 {id:"diluent",name:"Diluent",text:"A liquid used to dissolve a substance or spread it through more liquid. Adding water to juice is a simple example. That does not tell you which liquid works with a lab sample.",href:"/learn/vs/sterile-water",link:"Compare water-product labels"},
 {id:"concentration",name:"Concentration",text:"How much is in each amount of liquid. For example, 12 mg spread evenly through 4 mL gives 3 mg in each mL. The liquid added and the final liquid amount may differ.",href:"/tools/dose",link:"Calculate from a known concentration"},
 {id:"u-100",name:"U-100 scale",text:"A volume scale where 100 units equals 1 mL. So 10 units equals 0.1 mL. It does not tell you the amount in mg. Product IU are different: they measure an effect in a standard test, not liquid volume.",href:"/tools/syringe-units",link:"Convert U-100 units and mL"},
 {id:"subcutaneous",name:"Subcutaneous",text:"Below the skin. This word names a location. It is not advice to use a product that way. This website does not teach how to give an injection.",href:"/disclaimer",link:"Website scope and limitations"},
 {id:"sterile-water",name:"Sterile Water for Injection",text:"A specific labeled water product. Unlike BAC water, it has no added preservative to slow bacterial growth. It is also different from drinking water or ordinary distilled water. Check the full label.",href:"/learn/vs/sterile-water",link:"Sterile water versus bacteriostatic water"},
 {id:"mg",name:"Milligram (mg)",text:"A small unit of mass: how much material there is. A gram has 1,000 mg. One mg has 1,000 mcg. To find mL, you also need to know how much material is in each mL.",href:"/tools/mg-to-mcg",link:"Convert mass units"},
 {id:"mcg",name:"Microgram (mcg or μg)",text:"A unit of mass that is smaller than a milligram. One mg has 1,000 mcg. For example, 125 mcg equals 0.125 mg. The letters mcg and the symbol μg mean the same unit.",href:"/methodology",link:"Formulas and precision limits"},
];
export default function GlossaryPage(){return <div className="mx-auto max-w-3xl px-4 sm:px-6 pt-8 sm:pt-12 pb-24">
 <WebPageJsonLd name="BAC water and calculation glossary" description="Definitions for product labels and concentration arithmetic." url="/learn/glossary"/>
 <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Learning Center",href:"/learn"},{label:"Glossary",href:"/learn/glossary"}]}/>
 <p className="eyebrow">Plain-language reference</p><h1 className="mt-2 text-3xl sm:text-5xl font-serif">BAC water glossary</h1><p className="mt-4 leading-relaxed">Keep the number and its unit together. These definitions explain label language and the calculator's inputs. They do not select a product, dose, preparation method or treatment.</p>
 <nav aria-label="Glossary terms, A to Z" className="mt-6 flex flex-wrap gap-3 text-sm">{[...terms].sort((a,b)=>a.name.localeCompare(b.name)).map(t=><a key={t.id} href={'#'+t.id} className="inline-flex min-h-11 items-center rounded-lg border px-3 underline">{t.name}</a>)}</nav>
 <dl className="mt-7 divide-y">{[...terms].sort((a,b)=>a.name.localeCompare(b.name)).map(t=><div key={t.id} id={t.id} className="scroll-mt-24 py-6"><dt className="text-xl font-serif">{t.name}</dt><dd className="mt-3 space-y-3 leading-relaxed"><p>{t.text}</p><Link href={t.href} className="inline-block text-sm underline">{t.link}</Link></dd></div>)}</dl>
 <section className="mt-6 rounded-xl border p-5 text-sm leading-relaxed"><h2 className="text-lg font-semibold">Sources and limits</h2><p className="mt-3">Product terminology follows <a className="underline" href="https://www.pfizermedical.com/bacteriostatic-water">Pfizer's labeling</a>; the mass-prefix relationships follow <a className="underline" href="https://www.nist.gov/pml/owm/metric-si-prefixes">NIST's SI-prefix reference</a>. Checked September 22, 2026. These references do not verify a reader's preparation. Read our <Link href="/editorial-policy" className="underline">editorial policy</Link> and <Link href="/methodology" className="underline">calculation methodology</Link>.</p></section>
 </div>;}
