import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
export const metadata=withSocialMetadata({title:"BAC Water Glossary: Mass, Volume, Concentration and Label Terms",description:"Understand BAC water, benzyl alcohol, reconstitution, concentration, U-100 scale and related label terms. Definitions are not preparation or treatment instructions.",alternates:{canonical:"/learn/glossary"}});
const terms=[
 {id:"ml",name:"Milliliter (mL)",text:"One thousandth of a liter. It measures liquid volume. Converting volume to mass also requires the concentration of the named substance.",href:"/tools/syringe-units",link:"Convert U-100 volume units"},
 {id:"bacteriostatic-water",name:"Bacteriostatic water",text:"A pharmaceutical water preparation containing a bacteriostatic preservative. Read the exact label; the term does not establish compatibility with another product.",href:"/learn/what-is-bac-water",link:"Ingredients and labeled purpose"},
 {id:"benzyl-alcohol",name:"Benzyl alcohol",text:"A preservative used in the referenced bacteriostatic water formulations. Its concentration is product-specific. Preservative does not establish that a subsequently prepared mixture is sterile.",href:"/learn/vs/benzyl-alcohol",link:"Ingredient versus finished product"},
 {id:"bacteriostatic",name:"Bacteriostatic",text:"Describes inhibition of bacterial growth. It is not the same as sterilization, and it is not a guarantee against contamination.",href:"/learn/what-you-cannot-know",link:"Limits of a product label and calculator"},
 {id:"reconstitution",name:"Reconstitution",text:"Adding a specified liquid to a preparation that requires it. Product instructions establish the liquid and final volume; concentration arithmetic does not select them.",href:"/learn/how-peptide-reconstitution-works",link:"Reconstitution and concentration are different questions"},
 {id:"lyophilization",name:"Lyophilization",text:"Freeze-drying. The resulting powder still requires product-specific handling and storage instructions. The word alone does not establish stability or a discard date.",href:"/learn/how-to-read-a-peptide-vial",link:"Interpreting label information"},
 {id:"diluent",name:"Diluent",text:"The liquid used to dilute or dissolve a preparation. Different vehicles are not automatically interchangeable, even when their labels contain the word water.",href:"/learn/vs/sterile-water",link:"Compare water-product labels"},
 {id:"concentration",name:"Concentration",text:"The amount of a substance per unit of final volume. For example, 12 mg in a final 4 mL is 3 mg/mL. Volume added and final solution volume may differ.",href:"/tools/dose",link:"Calculate from a known concentration"},
 {id:"u-100",name:"U-100 scale",text:"A scale relationship of 100 units per mL. It does not state a substance's mass, the device capacity or the spacing of its smallest markings. Product activity units, such as hCG IU, are a different concept.",href:"/tools/syringe-units",link:"Convert U-100 units and mL"},
 {id:"subcutaneous",name:"Subcutaneous",text:"Below the skin. This is a route term, not a route recommendation for a particular product or person. This website does not provide administration instructions.",href:"/disclaimer",link:"Website scope and limitations"},
 {id:"sterile-water",name:"Sterile Water for Injection",text:"A labeled pharmaceutical preparation distinct from preserved bacteriostatic water and from ordinary distilled or drinking water. Verify the complete product name and intended use.",href:"/learn/vs/sterile-water",link:"Sterile water versus bacteriostatic water"},
 {id:"mg",name:"Milligram (mg)",text:"One thousandth of a gram. One milligram equals 1,000 micrograms. Mass does not convert directly to liquid volume without a concentration.",href:"/tools/mg-to-mcg",link:"Convert mass units"},
 {id:"mcg",name:"Microgram (mcg or μg)",text:"One millionth of a gram. Here, mcg is the text label for a microgram. For example, 125 mcg equals 0.125 mg.",href:"/methodology",link:"Formulas and precision limits"},
];
export default function GlossaryPage(){return <div className="mx-auto max-w-3xl px-4 sm:px-6 pt-8 sm:pt-12 pb-24">
 <WebPageJsonLd name="BAC water and calculation glossary" description="Definitions for product labels and concentration arithmetic." url="/learn/glossary"/>
 <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Learning Center",href:"/learn"},{label:"Glossary",href:"/learn/glossary"}]}/>
 <p className="eyebrow">Plain-language reference</p><h1 className="mt-2 text-3xl sm:text-5xl font-serif">BAC water glossary</h1><p className="mt-4 leading-relaxed">Keep the number and its unit together. These definitions explain label language and the calculator's inputs. They do not select a product, dose, preparation method or treatment.</p>
 <nav aria-label="Glossary terms, A to Z" className="mt-6 flex flex-wrap gap-3 text-sm">{[...terms].sort((a,b)=>a.name.localeCompare(b.name)).map(t=><a key={t.id} href={'#'+t.id} className="inline-flex min-h-11 items-center rounded-lg border px-3 underline">{t.name}</a>)}</nav>
 <dl className="mt-7 divide-y">{[...terms].sort((a,b)=>a.name.localeCompare(b.name)).map(t=><div key={t.id} id={t.id} className="scroll-mt-24 py-6"><dt className="text-xl font-serif">{t.name}</dt><dd className="mt-3 space-y-3 leading-relaxed"><p>{t.text}</p><Link href={t.href} className="inline-block text-sm underline">{t.link}</Link></dd></div>)}</dl>
 <section className="mt-6 rounded-xl border p-5 text-sm leading-relaxed"><h2 className="text-lg font-semibold">Sources and limits</h2><p className="mt-3">Product terminology follows <a className="underline" href="https://www.pfizermedical.com/bacteriostatic-water">Pfizer's labeling</a>; the mass-prefix relationships follow <a className="underline" href="https://www.nist.gov/pml/owm/metric-si-prefixes">NIST's SI-prefix reference</a>. Checked September 22, 2026. These references do not verify a reader's preparation. Read our <Link href="/editorial-policy" className="underline">editorial policy</Link> and <Link href="/methodology" className="underline">calculation methodology</Link>.</p></section>
 </div>;}
