import Link from "next/link";
import { prisma } from "@/lib/db";
import { safeJson } from "@/lib/seo/safe-json";
import { inlineMarkdown } from "@/lib/content/render";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";

export const metadata={title:"BAC Water FAQ: Ingredients, Storage and Calculator Limits",description:"Answers about BAC water labeling, final volume, U-100 scale, storage and saved calculations. Product-specific instructions remain separate from arithmetic.",alternates:{canonical:"/faq"}};
const questions=[
 {q:"What is BAC water (bacteriostatic water)?",a:"BAC water is short for bacteriostatic water, a pharmaceutical diluent containing a preservative. It is not interchangeable with every other water product or suitable for every substance.",href:"/learn/what-is-bac-water",label:"Read the ingredient and purpose reference"},
 {q:"What is BAC water used for?",a:"The product label describes dilution or dissolution of drugs according to the instructions for the exact preparation. The presence of preservative does not establish the sterility or stability of a mixture, and this site does not confirm compatibility.",href:"/learn/bac-water-for-peptides",label:"Separate product instructions from concentration math"},
 {q:"What is BAC water made of, and what is its pH?",a:"Pfizer's labeling describes water products containing 0.9% or 1.1% benzyl alcohol, with a labeled pH range of 4.5 to 7.0. Read the specific container. A numerical pH range or ingredient name does not establish suitability for your product.",href:"https://www.pfizermedical.com/bacteriostatic-water",label:"Read the manufacturer's labeling"},
 {q:"How much BAC water should I add to reconstitute a peptide?",a:"Vial strength alone cannot answer that question. Use the diluent and final-volume instructions for the exact product. The calculator checks concentration from numbers you supply; it does not select a preparation because it produces a convenient syringe mark.",href:"/tools/bac-water",label:"Check a known final volume"},
 {q:"What size insulin syringe should I use for peptides?",a:"This website does not select an administration device. Confirm the scale, capacity and graduation spacing from the actual device and product instructions. A U-100 scale represents 100 units per mL, but barrel capacity does not by itself tell you the spacing of its small marks.",href:"/learn/insulin-syringe-sizes",label:"Understand capacity and scale"},
 {q:"Does BAC water need to be refrigerated, and how long does it last?",a:"Follow the exact product's labeling rather than a blanket refrigeration rule. Pfizer's referenced water label specifies 20 to 25°C. Opened multi-dose vial dating and the storage limits of a reconstituted preparation are different questions. This website does not calculate a safe discard date.",href:"/learn/bac-water-shelf-life",label:"Read the storage distinctions and sources"},
 {q:"Do I need a prescription to buy BAC water?",a:"Check the exact labeled product and the requirements that apply where it is supplied. Ask a licensed pharmacist about a medicine-related purchase. BACwater.ai sells no water, peptides or other products and does not verify vendors.",href:"/learn/where-to-buy-bacteriostatic-water",label:"Questions to check before a purchase"},
 {q:"Is BAC water safe?",a:"Safety cannot be established by a calculator, the preservative, or the appearance of a vial. Suitability depends on the product, preparation, route and person. Follow qualified product-specific instructions; do not use this website to assess whether a preparation is safe to use.",href:"/learn/what-you-cannot-know",label:"What no calculation can verify"},
 {q:"Is BACwater.ai a medical service?",a:"No. It is a free arithmetic and reference website. It does not diagnose, prescribe, select a dose, sell products or verify a user's preparation.",href:"/methodology",label:"How the calculations work"},
 {q:"Do I need an account, and what can other people see?",a:"An account is not required for public calculations. Saving can store a plan on the creating device or in an account. Anyone receiving a shared calculation link can read the calculation. Private notes and custom plan names require owner access.",href:"/privacy",label:"Read the data and sharing policy"},
];
export default async function FaqPage(){
 const extra=await prisma.contentBlock.findMany({where:{kind:"faq",published:true},orderBy:{createdAt:"asc"}});
 const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:[...questions.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}})),...extra.map(f=>({"@type":"Question",name:f.title,acceptedAnswer:{"@type":"Answer",text:f.body.replace(/[*#`]/g,"")}}))]};
 return <div className="mx-auto max-w-3xl px-4 sm:px-6 pt-8 sm:pt-12 pb-24">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson(schema)}}/>
  <WebPageJsonLd name="BAC water frequently asked questions" description="Product-label context and the limits of the calculation tools." url="/faq"/>
  <Breadcrumbs items={[{label:"Home",href:"/"},{label:"FAQ",href:"/faq"}]}/>
  <p className="eyebrow">Help and reference</p><h1 className="mt-2 text-3xl sm:text-5xl font-serif">Frequently asked questions</h1>
  <p className="mt-4 leading-relaxed">Find the answer you need, then open the relevant guide or calculator. For a problem with the website, <Link href="/contact" className="underline">contact support</Link>. For a medication question, ask the dispensing professional.</p>
  <Accordion type="single" collapsible className="mt-6">{questions.map((f,i)=><AccordionItem key={f.q} value={`core-${i}`}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent><p>{f.a}</p><p className="mt-3"><Link href={f.href} className="underline">{f.label}</Link></p></AccordionContent></AccordionItem>)}</Accordion>
  {extra.length>0&&<section className="mt-8"><h2 className="text-xl font-serif">More questions from the content library</h2><Accordion type="single" collapsible className="mt-3">{extra.map(f=><AccordionItem key={f.id} value={f.id}><AccordionTrigger>{f.title}</AccordionTrigger><AccordionContent><div className="space-y-3">{f.body.split(/\n\n+/).map((s,i)=><p key={i} dangerouslySetInnerHTML={{__html:inlineMarkdown(s)}}/>)}</div></AccordionContent></AccordionItem>)}</Accordion></section>}
  <section className="mt-9 rounded-xl border p-5 text-sm leading-relaxed"><h2 className="text-lg font-semibold">Sources and review limits</h2><p className="mt-3">The product facts above use <a className="underline" href="https://www.pfizermedical.com/bacteriostatic-water">Pfizer's labeling</a> and <a className="underline" href="https://www.cdc.gov/injection-safety/hcp/clinical-safety/index.html">CDC injection-safety guidance</a>, checked September 22, 2026. FDA has separate <a className="underline" href="https://www.fda.gov/drugs/drug-alerts-and-statements/fdas-concerns-unapproved-glp-1-drugs-used-weight-loss">guidance on unapproved GLP-1 products</a>. A source check is not a qualified clinical review of this website.</p><p className="mt-3"><Link href="/editorial-policy" className="underline">Editorial policy</Link> · <Link href="/tools" className="underline">All calculators</Link></p></section>
 </div>;
}
