import { productDisplayName } from "@/lib/partners/supplier-catalog";
import Link from "next/link";
import { Wordmark } from "./wordmark";
import { ArrowRight, ArrowUpRight, Calculator, Scale, Ruler, FileText, LockKeyhole, Printer, BookOpen, Check, ChevronDown } from "lucide-react";
import type { ReactNode } from "react";
import { ResearchHero } from "./research-hero";
import styles from "./research-home.module.css";
const tools=[
 {id:"01",icon:Calculator,title:"Concentration",example:<>mg <span>÷</span> mL</>,text:"See how much is in each mL of liquid.",href:"/tools/bac-water",label:"Check concentration"},
 {id:"02",icon:Scale,title:"mg to mcg",example:<>mg <span>→</span> mcg</>,text:"Change mg to mcg, or mcg to mg.",href:"/tools/mg-to-mcg",label:"Change mg to mcg"},
 {id:"03",icon:Ruler,title:"Units to mL",example:<>units <span>↔</span> mL</>,text:"Change a U-100 reading to mL.",href:"/tools/syringe-units",label:"Convert U-100 units"}
];
const guides=[
 {number:"01",tag:"LABEL BASICS",title:"An amount isn't a concentration.",text:"What the number on a vial tells you, and what it doesn't.",href:"/learn/how-to-read-a-peptide-vial",symbol:"mg ≠ mg/mL"},
 {number:"02",tag:"MEASUREMENT",title:"Make sense of the marks.",text:"What the lines on a U-100 scale mean.",href:"/learn/what-syringe-units-mean",symbol:"100 units = 1 mL"},
 {number:"03",tag:"STORAGE & LIMITS",title:"How long does BAC water last?",text:"Understand expiry, opened-vial dating and refrigeration instructions.",href:"/learn/bac-water-shelf-life",symbol:"Check the label."}
];
export function ResearchHome({supplier}:{supplier?:ReactNode}){return <div className={styles.home}>
 <div className={styles.heroGround}><ResearchHero/><div className={styles.benefitRail}><p><Calculator size={16} aria-hidden="true"/>See how the math works.</p><p><FileText size={16} aria-hidden="true"/>Clear units. Visible steps.</p><p><LockKeyhole size={16} aria-hidden="true"/>Notes stay off shared links.</p></div></div>
 <section id="toolkit" className={styles.toolkit} aria-labelledby="toolkit-title"><div className={styles.sectionTop}><div><p className={styles.eyebrow}>A SMALL TOOLKIT. A CLEARER WORKFLOW.</p><h2 id="toolkit-title">The right tool.<br className={styles.mobileBreak}/> Less back and forth.</h2></div><Link href="/tools" className={styles.textLink}>All calculators <ArrowUpRight size={17} aria-hidden="true"/></Link></div>
 <div className={styles.toolGrid}>{tools.map(tool=><Link key={tool.id} href={tool.href} className={styles.toolCard}><div className={styles.toolTop}><tool.icon size={19} strokeWidth={1.4} aria-hidden="true"/><span>{tool.id}</span></div><div className={styles.toolExample} aria-hidden="true">{tool.example}</div><h3>{tool.title}</h3><p>{tool.text}</p><div className={styles.toolBottom}><span>{tool.label}</span><span className={styles.arrowCircle}><ArrowUpRight size={18} aria-hidden="true"/></span></div></Link>)}</div>
 <div className={styles.extraTools}><span>ALSO IN YOUR TOOLKIT</span><Link href="/tools/dose">Amount-to-volume <ArrowUpRight size={13} aria-hidden="true"/></Link><Link href="/tools/reverse-bac">Reverse volume <ArrowUpRight size={13} aria-hidden="true"/></Link><Link href="/tools/supplies">Vial counts <ArrowUpRight size={13} aria-hidden="true"/></Link></div>
 </section>
 <section id="saved-plans" className={styles.savedSection} aria-labelledby="saved-title"><div className={styles.savedCopy}><p className={styles.darkEyebrow}>CALCULATE. KEEP. COME BACK.</p><h2 id="saved-title">Keep the result.<br/>Not another <em>screenshot.</em></h2><p>Save the values you entered, add a private note, and turn your calculation into a PDF or printable label.</p><div className={styles.savedFeatures}><span><FileText size={16} aria-hidden="true"/>Saved calculations</span><span><LockKeyhole size={16} aria-hidden="true"/>Private notes</span><span><Printer size={16} aria-hidden="true"/>PDFs & labels</span></div><Link href="/plan" className={styles.limeButton}>Build a saved plan <ArrowUpRight size={17} aria-hidden="true"/></Link><p className={styles.shareNote}>Shared links show the calculation, not your private notes.</p></div>
 <div className={styles.recordScene} aria-label="Illustrative saved calculation, not an actual account record"><div className={styles.record}><div className={styles.recordHeader}><Wordmark/><span>EXAMPLE RECORD</span></div><div className={styles.recordTitle}><FileText size={18} aria-hidden="true"/><h3>Concentration calculation</h3></div><dl><div><dt>Stated amount</dt><dd>12 mg</dd></div><div><dt>Final volume</dt><dd>4 mL</dd></div><div><dt>Concentration</dt><dd>3 mg/mL</dd></div></dl><p className={styles.recordFormula}>12 mg ÷ 4 mL = 3 mg/mL</p><div className={styles.privateNote}><LockKeyhole size={14} aria-hidden="true"/><span><strong>Private note</strong><br/>Notes stay off your shared link.</span></div><p className={styles.recordLimit}>Illustrative values. Not product instructions.</p></div><div className={styles.labelCard} aria-hidden="true"><span>CALCULATION LABEL</span><strong>3 <small>mg/mL</small></strong><div>12 mg / final 4 mL</div><p>EXAMPLE ONLY</p></div></div></section>
 {supplier}
 <section id="learn" className={styles.learn} aria-labelledby="learn-title"><div className={styles.sectionTop}><div><p className={styles.eyebrow}>A LITTLE CONTEXT GOES A LONG WAY.</p><h2 id="learn-title">Understand the label.<br/>Then check the numbers.</h2></div><Link href="/learn" className={styles.textLink}>Visit the learning center <ArrowUpRight size={17} aria-hidden="true"/></Link></div><div className={styles.guideGrid}>{guides.map(guide=><Link key={guide.number} href={guide.href} className={styles.guide}><div className={styles.guideNumber}><span>{guide.number} / FIELD NOTES</span><BookOpen size={16} aria-hidden="true"/></div><p className={styles.guideSymbol}>{guide.symbol}</p><p className={styles.guideTag}>{guide.tag}</p><h3>{guide.title}</h3><p className={styles.guideText}>{guide.text}</p><span className={styles.guideRead}>Read the guide <ArrowRight size={16} aria-hidden="true"/></span></Link>)}</div>
 <details className={styles.context}><summary><span>Before you use a calculator</span><ChevronDown size={18} aria-hidden="true"/></summary><div className={styles.contextBody}><div><h3>A vial amount is not a concentration.</h3><p>A label that states 10 mg describes an amount. In a final volume of 2 mL, the concentration would be 5 mg/mL. That example does not tell you to add 2 mL to a particular product.</p><p>BAC water is a pharmaceutical diluent containing a preservative. Formulation and intended use depend on the exact label. Preservative does not prove a prepared mixture is sterile or stable.</p><p><Link href="/learn/what-is-bac-water">Ingredients and intended purpose</Link> · <a href="https://www.pfizermedical.com/bacteriostatic-water">Product labeling reference</a></p></div><div><h3>Three checks before calculating</h3><ol><li>Copy each number with its unit. mg and mcg describe mass; mL describes volume.</li><li>Use the final volume from your instructions. Vial strength alone does not determine a suitable dilution.</li><li>Check the actual device scale. U-100 means 100 units per mL, not a universal conversion for every syringe.</li></ol><Link href="/methodology">See formulas and limits</Link></div></div></details>
 </section>
 <section className={styles.references} aria-labelledby="reference-title"><div><p className={styles.eyebrow}>LOOK UP. DON'T GUESS.</p><h2 id="reference-title">Compound references</h2><p>Look up a name. This list is not advice about what to use.</p></div><div><div className={styles.compoundLinks}>{[["bpc-157","BPC-157"],["tb-500","TB-500"],["semaglutide","Semaglutide"],["tirzepatide","Tirzepatide"],["retatrutide","Retatrutide"],["ghk-cu","GHK-Cu"]].map(([slug,label])=><Link key={slug} href={`/peptides/${slug}`}>{productDisplayName(slug,label)}<ArrowUpRight size={13} aria-hidden="true"/></Link>)}</div><p className={styles.referenceLinks}><Link href="/peptides">All compounds</Link><Link href="/peptides/compare">Compare label context</Link><Link href="/learn/vs/sterile-water">BAC water vs sterile water</Link></p></div></section>
 <section className={styles.finalCta}><div><p className={styles.eyebrow}>START WITH WHAT YOU KNOW.</p><h2>A clearer result starts<br/>with your numbers.</h2></div><div><Link href="/peptide-calculator" className={styles.darkButton}>Open the calculator <ArrowUpRight size={19} aria-hidden="true"/></Link><p><Check size={13} aria-hidden="true"/> Free calculations. No account required.</p></div></section>
</div>;}
