import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
import { PreferredSourceButton } from "@/components/common/preferred-source-button";
import { preferredSourceDeeplink } from "@/lib/preferred-source";
const title = "Choose BACwater.ai as a Preferred Source on Google";
const description = "Learn how to find BACwater.ai in Google's source preferences, what the setting changes, and how to remove a preference later.";
export const metadata = withSocialMetadata({ title, description, alternates: { canonical: "/preferred-source" }, openGraph: { title, description, url: "/preferred-source", type: "website" } });
export default function PreferredSourcePage() {
  return <article className="mx-auto max-w-3xl px-4 sm:px-6 pt-10 sm:pt-16 pb-20">
    <WebPageJsonLd name={title} description={description} url="/preferred-source"/><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Preferred source on Google", href: "/preferred-source" }]}/>
    <p className="eyebrow">Google Search preferences</p><h1 className="mt-2 text-4xl sm:text-5xl font-serif tracking-tight">Prefer BACwater.ai on Google.</h1>
    <p className="mt-5 text-lg leading-relaxed">If our calculation tools and reference guides help you, you can look for BACwater.ai in Google's source preferences. You choose the sources you want highlighted. Availability and the results you see are controlled by Google.</p>
    <div className="section-dark mt-8 rounded-2xl p-6"><h2 className="text-xl font-serif">Open your source preferences</h2><PreferredSourceButton className="mt-4" theme="dark"/><p className="mt-4 text-sm">If the button is unavailable, <a className="underline" href={preferredSourceDeeplink()} target="_blank" rel="noopener noreferrer">open the plain Google preferences link</a>.</p></div>
    <section className="mt-10 space-y-4"><h2 className="text-2xl font-serif">What the setting changes</h2><p>Google describes preferred sources as a way to personalize Top Stories, AI Mode and AI Overviews. Relevant, fresh content from chosen sources can appear more often in Top Stories, and preferred sources can be highlighted in AI features. This does not guarantee that a calculator or guide will appear for any particular search.</p><p>Some sources may be unavailable, including sites that are not updated regularly. If BACwater.ai is not listed, you can still bookmark a <Link href="/tools" className="underline">calculation tool</Link> or <Link href="/learn" className="underline">guide</Link> directly.</p></section>
    <section className="mt-10 space-y-4"><h2 className="text-2xl font-serif">Add or remove a source</h2><ol className="list-decimal space-y-3 pl-5"><li>Open Google Search. In your profile menu, look for Search personalization, then Source preferences.</li><li>Search for BACwater.ai and select its checkbox if the source is available.</li><li>Return to the same settings to deselect a source. When you save preferences while signed in, they apply in browsers signed into that Google account.</li></ol><p className="text-sm text-muted-foreground">Instructions checked September 25, 2026 against <a className="underline" href="https://support.google.com/websearch/answer/16379181?hl=en" target="_blank" rel="noopener noreferrer">Google's preferred sources help</a>. Interface details can change.</p></section>
    <section className="mt-10 space-y-4"><h2 className="text-2xl font-serif">Know the source you are choosing</h2><p>BACwater.ai provides free deterministic arithmetic and reference material. It also has an independent affiliate directory and may earn commissions from linked purchases. Calculator results do not verify product contents, compatibility, sterility or stability.</p><p>Read our <Link className="underline" href="/methodology">formulas and checks</Link>, <Link className="underline" href="/editorial-policy">editorial policy</Link> and <Link className="underline" href="/about">publisher information</Link> to decide whether the site is useful to you.</p></section>
  </article>;
}
