import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
import type { Metadata } from "next";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
export const metadata: Metadata = withSocialMetadata({ title: "Calculator Methodology: Formulas, Units and Limits", description: "Check the formulas behind BACwater.ai: mg to mcg, concentration, measured volume and syringe scales. Worked examples, rounding limits and verification cases.", alternates: { canonical: "/methodology" } });
export default function Methodology() {
 return <article className="mx-auto max-w-3xl px-4 pb-24 pt-10 sm:px-6">
  <WebPageJsonLd name="Calculator methodology" description="The formulas, assumptions and limits used by BACwater.ai." url="/methodology" />
  <Breadcrumbs items={[{label:"Home",href:"/"},{label:"Calculator methodology",href:"/methodology"}]} />
  <div className="eyebrow">How the numbers work</div><h1 className="mt-3 text-4xl font-serif sm:text-5xl">Calculator formulas, with checks you can repeat.</h1>
  <p className="mt-5 text-lg leading-relaxed">BACwater.ai converts numbers you supply. It does not decide which substance, diluent, amount or schedule is appropriate. A correct calculation cannot verify a product or establish its shelf life.</p>
  <p className="mt-3 text-sm text-muted-foreground">Methodology updated September 21, 2026. Arithmetic examples below are not preparation or treatment instructions.</p>
  <nav aria-label="On this page" className="my-8 flex flex-wrap gap-x-5 gap-y-3 text-sm underline"><a href="#mass">Mass</a><a href="#concentration">Concentration</a><a href="#scales">Syringe scales</a><a href="#limits">Precision and limits</a><a href="#checks">Verification</a></nav>
  <section id="mass" className="scroll-mt-24 space-y-3"><h2 className="text-2xl font-serif">Mass: milligrams and micrograms</h2><p>A milligram is 1,000 micrograms. Multiply mg by 1,000 to obtain mcg; divide mcg by 1,000 to obtain mg. These are mass units, not liquid volumes.</p><p className="rounded-xl border p-4 font-mono break-words">0.125 mg × 1,000 = 125 mcg</p><p>The <Link href="/tools/mg-to-mcg" className="underline">mass converter</Link> shifts decimal digits as text, so an accepted decimal does not acquire a binary floating-point rounding error during that conversion. Scientific notation is accepted within the displayed range. The <a href="https://www.nist.gov/pml/owm/metric-si-prefixes" className="underline" rel="noreferrer">NIST SI-prefix reference</a> defines milli and micro.</p></section>
  <section id="concentration" className="mt-9 scroll-mt-24 space-y-3"><h2 className="text-2xl font-serif">Concentration and measured volume</h2><p>Concentration equals total mass divided by final solution volume. Measured volume equals the stated amount divided by that concentration. The calculator assumes the stated material is fully dissolved and uniformly distributed.</p><div className="rounded-xl border p-4 space-y-2 font-mono break-words"><p>12 mg ÷ 4 mL = 3 mg/mL</p><p>0.3 mg ÷ 3 mg/mL = 0.1 mL</p></div><p>Final volume and the volume of liquid added are not necessarily identical. Use the final volume supplied by the relevant instructions or measurement. The tool cannot infer displacement, compatibility, purity, losses or a vial&apos;s physical capacity.</p><p>Changing the final volume changes concentration. It does not create more material: before accounting for losses, 12 mg contains forty 0.3 mg portions whether the final volume is 4 mL or 6 mL. A count is not a treatment schedule.</p><Link href="/tools/bac-water" className="inline-flex min-h-11 items-center underline">Check a stated final volume</Link></section>
  <section id="scales" className="mt-9 scroll-mt-24 space-y-3"><h2 className="text-2xl font-serif">Syringe scale is separate from capacity</h2><p>On a U-100 scale, 100 units represent 1 mL. The scale relationship stays the same on a 0.3 mL, 0.5 mL or 1 mL U-100 syringe. Capacity is the maximum volume; tick spacing is the actual graduation interval. Neither is a milligram amount.</p><p className="rounded-xl border p-4 font-mono break-words">0.1 mL × 100 = 10 U-100 units</p><p>A different scale requires a different conversion. International units of a biological product are not syringe-volume markings and do not have one universal conversion to mg. Match the actual product and device instructions; do not use this illustration to choose a device or an injection technique.</p><Link href="/tools/syringe-units" className="inline-flex min-h-11 items-center underline">Open the U-100 converter</Link></section>
  <section id="limits" className="mt-9 scroll-mt-24 space-y-3"><h2 className="text-2xl font-serif">Precision, rounding and storage limits</h2><p>The planning engine uses JavaScript numbers for multiplication and division. Display formatting may round values. It is not a claim of laboratory measurement accuracy, and a highlighted mark is not a calibration certificate. Validate the actual graduations, product concentration and intended amount separately.</p><p>Inputs must be finite and positive where required. A whole-portion count rounds down, allowing a small floating-point tolerance only at an integer boundary. Very large counts and non-finite results are rejected rather than presented as reliable plans.</p><p>Mixing dates are records only. Labels and PDFs do not create a safe discard date. The <Link href="/learn/bac-water-shelf-life" className="underline">storage reference</Link> explains why the exact formulation matters. Saved links let their recipients read the calculation; private notes require owner access.</p></section>
  <section id="checks" className="mt-9 scroll-mt-24 space-y-3"><h2 className="text-2xl font-serif">Repeatable verification cases</h2><div role="region" aria-label="Calculator verification examples" tabIndex={0} className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><caption className="p-4 text-left">Compound-neutral arithmetic fixtures</caption><thead><tr><th scope="col" className="p-4">Input</th><th scope="col" className="p-4">Expected result</th></tr></thead><tbody><tr className="border-t"><th scope="row" className="p-4">0.000001 mg</th><td className="p-4">0.001 mcg</td></tr><tr className="border-t"><th scope="row" className="p-4">10 mg in 2 mL; 400 mcg amount</th><td className="p-4">5 mg/mL; 0.08 mL; 8 U-100 units</td></tr><tr className="border-t"><th scope="row" className="p-4">25 U-100 units</th><td className="p-4">0.25 mL</td></tr></tbody></table></div><p>Software tests cover these relationships, invalid inputs, shared-plan permissions and publication behavior. Passing software tests is not clinical validation. Report an incorrect result through <Link href="/contact" className="underline">Contact</Link> with the units and reproducible steps, without personal medical information or private share links.</p></section>
 <section className="mt-9 rounded-xl border p-5"><h2 className="text-xl font-serif">Publisher and corrections</h2><p className="mt-3 leading-relaxed">BACwater.ai publishes these tools and references. For a calculation error or factual correction, <Link className="underline" href="/contact">contact the BACwater.ai website support team</Link> with the public page and the source or steps needed to check it. Editorial attribution does not imply clinical review.</p></section></article>;
}
