import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
import { ArrowUpRight, Calculator, Droplets, Scale, Ruler, Package, RotateCcw, FileText, Beaker } from "lucide-react";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
import { WebPageJsonLd } from "@/components/common/webpage-json-ld";
export const metadata=withSocialMetadata({title:"Free BAC Water and Peptide Calculators",description:"Check your label numbers. Find concentration, convert mg and mcg, check U-100 units, count vials, or save a plan.",alternates:{canonical:"/tools"}});
const tools=[
 {href:"/tools/bac-water",icon:Droplets,title:"Check BAC water math",body:"Enter the vial amount and final liquid volume. See how much is in each mL.",example:"mg ÷ mL"},
 {href:"/tools/mg-to-mcg",icon:Scale,title:"Change mg to mcg",body:"Switch between these two ways to write an amount. Either way works.",example:"mg ↔ mcg"},
 {href:"/tools/syringe-units",icon:Ruler,title:"Change units to mL",body:"Check a U-100 scale. On that scale, 100 units is 1 mL.",example:"units ↔ mL"},
 {href:"/tools/dose",icon:Beaker,title:"Amount-to-volume",body:"Already know the concentration? Check the amount in a volume, or the volume for an amount.",example:"amount ÷ mg/mL"},
 {href:"/tools/supplies",icon:Package,title:"Count your vials",body:"Use your own amounts and count. See how many whole vials the math calls for.",example:"count → vials"},
 {href:"/tools/reverse-bac",icon:RotateCcw,title:"Try a different volume",body:"Explore how the numbers change. This does not tell you how to prepare a product.",example:"volume ↔ scale"},
 {href:"/tools/vial-labels",icon:FileText,title:"Print a label",body:"Keep the numbers with the vial. Make a label from a saved plan.",example:"save → print"},
];
export default function ToolsPage(){return <div className="mx-auto max-w-6xl px-4 sm:px-6 pt-9 pb-12"><WebPageJsonLd name="Free calculators" description="Tools for entered label numbers and measurement math." url="/tools"/><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Calculators",href:"/tools"}]}/><p className="eyebrow">Choose a task</p><h1 className="mt-3 font-serif">What would you like to check?</h1><p className="mt-4 max-w-2xl leading-relaxed">Use the full calculator, or pick a small tool below. You do not need an account.</p><Link href="/peptide-calculator" className="bac-featured-tool"><div><span className="eyebrow">START HERE</span><h2>The full peptide calculator</h2><p>Put in your label numbers. See the result. Save or print it.</p></div><span className="bac-featured-action"><Calculator size={20} aria-hidden="true"/>Open calculator<ArrowUpRight size={19} aria-hidden="true"/></span></Link><div className="bac-tools-grid">{tools.map(t=><Link key={t.href} href={t.href} className="bac-tool-tile"><div className="bac-tile-top"><t.icon size={22} aria-hidden="true"/><span>{t.example}</span></div><h2>{t.title}</h2><p>{t.body}</p><span className="bac-tile-action">Open tool <ArrowUpRight size={19} aria-hidden="true"/></span></Link>)}</div><div className="bac-info-card mt-8"><h2>Not sure what a unit means?</h2><p><strong>mg and mcg</strong> tell you the amount of material. <strong>mL</strong> tells you the amount of liquid. <strong>mg/mL</strong> tells you how much material is in each mL.</p><p>This site checks math. It does not choose a dose, liquid, or treatment. <Link href="/learn/glossary" className="underline">See the word guide</Link>.</p></div></div>;}
