"use client";
import { CalculatorWorkspace } from "@/components/calculator/calculator-workspace";
import { SupplyChecklist } from "@/components/tools/supply-checklist";
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { usePersistentState } from "@/lib/use-persistent-state";
interface ConversionInput{direction:"units"|"ml";text:string}
function display(n:number){return n!==0&&(n<0.000001||n>=1e9)?n.toExponential(11).replace(/\.?0+e/,"e"):new Intl.NumberFormat("en-US",{maximumSignificantDigits:12,useGrouping:false}).format(n);}
export default function SyringeUnitConverterPage(){
 const [stored,setStored]=usePersistentState<ConversionInput>("bacwater.tool.syringe.conversion.v2",{direction:"units",text:""});
 const text=typeof stored?.text==="string"?stored.text:"",direction=stored?.direction==="ml"?"ml":"units";
 const value=Number(text),hasInput=text.trim().length>0;
 const other=direction==="units"?value/100:value*100;
 const valid=hasInput&&text.length<=64&&/^\+?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d{1,3})?$/i.test(text.trim())&&value>=0&&Number.isFinite(value)&&Number.isFinite(other)&&(value===0||other>0);
 const units=direction==="units"?text:valid?display(other):"",ml=direction==="ml"?text:valid?display(other):"";
 const invalid=hasInput&&!valid;
 return <CalculatorWorkspace title="U-100 syringe units to mL" description="On a U-100 scale, 100 units = 1 mL and 1 unit = 0.01 mL. Enter either value to convert it." help={<SupplyChecklist/>} reference={<> <section className="mt-9"><h2 className="text-2xl font-serif">U-100 conversion examples</h2><div className="mt-4 rounded-xl border"><table className="w-full text-left text-sm"><caption className="sr-only">U-100 scale units and liquid volumes</caption><thead><tr><th scope="col" className="p-3">U-100 units</th><th scope="col" className="p-3">Volume</th></tr></thead><tbody>{[1,5,10,20,25,30,40,50,75,100,200].map(n=><tr key={n} className="border-t"><th scope="row" className="p-3 font-normal">{n}</th><td className="p-3">{n/100} mL</td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-muted-foreground">These are mathematical equivalents. For example, 200 U-100 units equal 2 mL, which exceeds a 1 mL syringe's capacity.</p></section>
 <section className="mt-9 space-y-3"><h2 className="text-2xl font-serif">How many U-100 units are in 0.5 mL?</h2><p>0.5 mL × 100 = 50 U-100 units. To check the reverse calculation, divide 50 by 100 to get 0.5 mL. The same ratio gives 25 units for 0.25 mL and 10 units for 0.1 mL.</p></section>
 <section className="mt-9 space-y-3"><h2 className="text-2xl font-serif">Can you convert mg directly to syringe units?</h2><p>No. Milligrams measure mass, while the U-100 scale corresponds to volume. You also need the concentration in mg/mL. Divide your stated amount by that concentration to get mL, then multiply mL by 100 for the U-100 scale equivalent.</p><p>For example, a stated amount of 0.5 mg at 2 mg/mL corresponds to 0.25 mL, or 25 U-100 units. These are illustrative numbers, not a recommended amount or device.</p><Link href="/tools/dose" className="inline-flex min-h-11 items-center underline">Convert an amount using a known concentration</Link></section>
 <section className="mt-9 space-y-3"><h2 className="text-2xl font-serif">Scale, capacity and markings are different</h2><p>U-100 defines the conversion ratio. The capacity states how much liquid a device holds. The graduation spacing describes its printed intervals. Confirm all three from the actual device instructions rather than inferring them from barrel size.</p><p>A converter does not select a dose, an administration device or a treatment. mg and mcg describe mass, not scale markings; converting mass to mL also requires concentration.</p><p><Link href="/tools/dose" className="underline">Known concentration tool</Link> · <Link href="/tools/mg-to-mcg" className="underline">Mass converter</Link> · <Link href="/methodology" className="underline">Formulas and limits</Link></p></section>
 </>}>
 <section className="rounded-2xl border bg-card p-5 sm:p-7" aria-label="U-100 volume conversion"><div className="grid gap-5 sm:grid-cols-2">
 <div><label htmlFor="u100-units" className="block text-sm font-medium">U-100 syringe units</label><Input id="u100-units" type="text" inputMode="decimal" maxLength={64} value={units} onChange={e=>setStored({direction:"units",text:e.target.value})} aria-invalid={invalid&&direction==="units"} aria-describedby="u100-help u100-error" placeholder="For example, 25" className="mt-2 min-h-12"/></div>
 <div><label htmlFor="u100-ml" className="block text-sm font-medium">Milliliters (mL)</label><Input id="u100-ml" type="text" inputMode="decimal" maxLength={64} value={ml} onChange={e=>setStored({direction:"ml",text:e.target.value})} aria-invalid={invalid&&direction==="ml"} aria-describedby="u100-help u100-error" placeholder="For example, 0.25" className="mt-2 min-h-12"/></div></div>
 <p id="u100-help" className="mt-3 text-sm text-muted-foreground">mL = U-100 units ÷ 100. U-100 units = mL × 100.</p><p id="u100-error" role={invalid?"alert":undefined} className="mt-2 text-sm text-destructive">{invalid?"Enter a finite, non-negative decimal within the supported numeric range. No conversion is shown for an invalid input.":""}</p>
 <div className="mt-4 rounded-xl bg-muted p-4" role="status" aria-live="polite" aria-atomic="true"><p className="text-lg font-semibold [overflow-wrap:anywhere]">{valid?`${display(direction==="units"?value:other)} U-100 units = ${display(direction==="ml"?value:other)} mL`:"Enter a value to see the conversion."}</p></div>
 <div className="mt-4 flex flex-wrap gap-3"><Button type="button" variant="outline" onClick={()=>setStored({direction:"units",text:""})}>Clear values</Button><Button asChild variant="brand"><Link href="/peptide-calculator">Open the full calculator</Link></Button></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Up to 12 significant digits are displayed. Very small and large results use scientific notation. A value that would overflow or round down to zero is rejected. Confirm the actual device capacity and markings separately.</p></section>
 </CalculatorWorkspace>;
}
