import Link from 'next/link';
import { EmbedPreview } from '@/components/growth/embed-preview';
import { ShareToolButton } from '@/components/common/share-tool-button';
import { withSocialMetadata } from '@/lib/seo/social-metadata';
import { Breadcrumbs } from '@/components/common/breadcrumbs';
import { WebPageJsonLd } from '@/components/common/webpage-json-ld';
export const metadata = withSocialMetadata({ title: 'Free Calculator Embed and Unit Reference Cards', description: 'Add a free mg to mcg converter to your website, or share original unit reference cards. No account, API key or paid plan required.', alternates: { canonical: '/share-tools' } });
const cards = [
  { id: 'mg-to-mcg', title: 'mg and mcg', alt: 'Mass conversion reference: 1 mg equals 1,000 mcg; 0.125 mg equals 125 mcg.', href: '/tools/mg-to-mcg', text: 'Two units for the same mass. Multiply mg by 1,000 to get mcg.' },
  { id: 'u100-to-ml', title: 'U-100 and mL', alt: 'U-100 scale reference: 100 units equals 1 mL; 25 units equals 0.25 mL.', href: '/tools/syringe-units', text: 'A U-100 scale has 100 units per mL. It does not specify mass or product IU.' },
  { id: 'concentration', title: 'Mass and final volume', alt: 'Concentration example: 12 mg divided by a final volume of 4 mL equals 3 mg per mL.', href: '/tools/bac-water', text: 'Divide mass by the final solution volume. The example is arithmetic, not preparation instructions.' },
];
export default function ShareToolsPage() {
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6">
    <WebPageJsonLd name="Free calculator embed and reference cards" description="Shareable calculation tools and original unit reference graphics." url="/share-tools"/>
    <Breadcrumbs items={[{label:'Home',href:'/'},{label:'Calculators',href:'/tools'},{label:'Share tools',href:'/share-tools'}]}/>
    <p className="eyebrow">Useful tools, easy to share</p>
    <h1 className="mt-3 max-w-3xl font-serif text-4xl sm:text-5xl">Bring clear calculation tools to your readers.</h1>
    <p className="mt-5 max-w-2xl leading-relaxed">Add a free mass converter to your website or share a unit reference card. No account, API key or subscription is required.</p>
    <div className="mt-6 flex flex-wrap gap-3"><ShareToolButton path="/share-tools"/><Link href="/tools" className="inline-flex min-h-11 items-center rounded-lg border px-4">Browse all calculators</Link></div>
    <section className="mt-12 grid items-start gap-8 lg:grid-cols-2" aria-labelledby="embed-title">
      <div><p className="eyebrow">A small tool for your website</p><h2 id="embed-title" className="mt-3 font-serif text-3xl">Free mg to mcg converter</h2><p className="mt-4 leading-relaxed">Readers can convert mass units without leaving your page. The converter uses the same decimal conversion logic as BACwater.ai and keeps its styling separate from your site.</p><ul className="mt-5 list-disc space-y-2 pl-5"><li>Works at mobile and desktop widths.</li><li>No advertising, affiliate links or tracking inside the widget.</li><li>Entered values stay in the reader&apos;s browser; they are not sent to BACwater.ai.</li><li>A visible link opens the full converter and its explanation.</li></ul><p className="mt-5 text-sm">Loading the script makes a normal request to our server. Your own website&apos;s privacy practices still apply. See <Link className="underline" href="/privacy">privacy details</Link>.</p></div>
      <EmbedPreview/>
    </section>
    <section className="mt-14" aria-labelledby="cards-title"><p className="eyebrow">Save, explain, share</p><h2 id="cards-title" className="mt-3 font-serif text-3xl">Unit reference cards</h2><p className="mt-4 max-w-2xl">These original graphics are free to share unchanged in educational posts, newsletters and resource pages. Keep the BACwater.ai attribution and limitations visible. A source link is appreciated. No endorsement is implied.</p>
      <div className="mt-7 grid gap-6 md:grid-cols-3">{cards.map(card => <article key={card.id} className="overflow-hidden rounded-2xl border border-border bg-card"><img src={`/growth/${card.id}.png`} width={1000} height={1500} alt={card.alt} loading="lazy" className="h-auto w-full"/><div className="space-y-3 p-5"><h3 className="font-serif text-2xl">{card.title}</h3><p className="text-sm leading-relaxed">{card.text}</p><div className="flex flex-wrap gap-4 text-sm"><a href={`/growth/${card.id}.png`} download className="inline-flex min-h-11 items-center underline">Download PNG</a><Link href={card.href} className="inline-flex min-h-11 items-center underline">Open calculator</Link></div></div></article>)}</div>
    </section>
    <section className="mt-12" aria-labelledby="video-title"><h2 id="video-title" className="font-serif text-3xl">A short guide to mg and mcg</h2><p className="mt-3 mb-5">A silent, captioned explanation of the conversion. All examples are illustrative.</p><video controls preload="none" poster="/growth/mg-to-mcg-video-poster.png" className="w-full max-w-3xl rounded-2xl border" width={1280} height={720} aria-label="mg to mcg: a 32-second visual explanation"><source src="/growth/mg-to-mcg-explained.mp4" type="video/mp4"/><track kind="captions" src="/growth/mg-to-mcg-explained.vtt" srcLang="en" label="English"/>Your browser does not support inline video.</video><details className="mt-4 max-w-3xl rounded-xl border p-4"><summary className="cursor-pointer">Read the video transcript</summary><p className="mt-3">mg and mcg are two units for the same mass. One milligram equals 1,000 micrograms. Multiply milligrams by 1,000. The unit changes; the mass stays the same. For example, 0.125 mg equals 125 mcg. To reverse it, divide 125 by 1,000 to get 0.125 mg. Try your own numbers in the free mg to mcg converter. Mass conversion only; no dose is selected.</p></details><a href="/growth/mg-to-mcg-explained.mp4" download className="mt-3 inline-flex min-h-11 items-center underline">Download the video</a></section>
    <section className="mt-12 rounded-2xl border border-border p-6"><h2 className="font-serif text-2xl">Share a tool without sharing your numbers</h2><p className="mt-3 max-w-3xl">Use the share icon in a calculator&apos;s top bar to send a clean tool link. Your entries and notes are excluded. Sharing a saved plan is different: anyone with that link can read its calculation.</p><p className="mt-3 text-sm">These tools explain arithmetic. They do not select a dose, product, diluent, preparation or treatment. Research products are not for human or veterinary use.</p></section>
  </div>;
}
