import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {chromium,expect} from '@playwright/test';
import {PrismaClient} from '@prisma/client';
const origin=process.env.AUDIT_ORIGIN,db=new URL(process.env.DATABASE_URL||'postgresql://invalid/invalid');
assert.equal(origin,'http://127.0.0.1:3000');assert.equal(db.hostname,'127.0.0.1');assert.equal(db.pathname,'/bacwater_audit');
const out='audit-evidence/consent';await fs.mkdir(out,{recursive:true});const prisma=new PrismaClient(),browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:390,height:844}}),requests=[],results=[],errors=[];
const prefix=`consent-${Date.now()}`,email=`${prefix}@example.test`;
await context.addCookies([{name:'bacwater_age_ok',value:'1',url:origin}]);
await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin===origin)return r.continue();requests.push({host:u.hostname,path:u.pathname});if(u.hostname==='www.googletagmanager.com'&&u.pathname==='/gtag/js')return r.fulfill({status:200,contentType:'application/javascript',body:'/* Deliberately no provider code: inspect the real application queue only. */'});return r.abort();});
const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
const calls=()=>page.evaluate(()=>Array.from(window.dataLayer||[],x=>Array.from(x)));
async function step(name,fn){try{await fn();results.push({name,status:'passed'});}catch(e){results.push({name,status:'failed',error:String(e)});throw e;}}
try{
 await step('Default denied state does not request an analytics script',async()=>{await page.goto(origin+'/contact');await expect(page.getByRole('button',{name:'Allow usage analytics',exact:true})).toBeVisible();assert.equal(requests.some(r=>r.host==='www.googletagmanager.com'),false);assert.equal((await calls()).filter(x=>x[0]==='event').length,0);});
 // The application queues its page view before the async script request is observable.
 // Wait for that request explicitly; still require exactly one after consent.
 await step('Explicit grant produces one sanitized manual page view',async()=>{await page.getByRole('button',{name:'Allow usage analytics',exact:true}).click();await expect.poll(async()=>(await calls()).filter(x=>x[0]==='event'&&x[1]==='page_view').length).toBe(1);const event=(await calls()).find(x=>x[1]==='page_view');assert.equal(event[2].page_location,'https://bacwater.ai/contact');assert.equal(event[2].page_referrer,'');assert.equal(event[2].page_title,'BACwater.ai utility');await expect.poll(()=>requests.filter(r=>r.host==='www.googletagmanager.com').length,{timeout:5000}).toBe(1);});
 await step('Stored contact succeeds before its usage event, without form values in analytics',async()=>{await page.getByLabel('Name',{exact:true}).fill(prefix);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Message',{exact:true}).fill('Controlled consent and record verification fixture.');await page.getByRole('button',{name:'Send message',exact:true}).click();await expect(page.getByRole('heading',{name:'Your message has been saved.'})).toBeVisible();assert.equal(await prisma.contactMessage.count({where:{email}}),1);await expect.poll(async()=>(await calls()).filter(x=>x[0]==='event'&&x[1]==='contact_saved').length).toBe(1);const text=JSON.stringify(await calls());assert.equal(text.includes(email),false);assert.equal(text.includes(prefix),false);assert.equal(text.includes('verification fixture'),false);});
 await step('Compound and query information do not enter the page-view queue',async()=>{await page.goto(origin+'/peptides/hcg?private_test=not-for-analytics');await expect.poll(async()=>(await calls()).filter(x=>x[1]==='page_view').length).toBe(1);const text=JSON.stringify(await calls());assert.ok(text.includes('https://bacwater.ai/peptides/reference'));assert.equal(text.includes('hcg'),false);assert.equal(text.includes('not-for-analytics'),false);});
 await step('Account routes do not start analytics even after public-page consent',async()=>{const before=requests.filter(r=>r.host==='www.googletagmanager.com').length;await page.goto(origin+'/plans');assert.equal((await calls()).filter(x=>x[0]==='event').length,0);assert.equal(requests.filter(r=>r.host==='www.googletagmanager.com').length,before);});
 await step('Revocation disables collection and removes first-party GA cookies',async()=>{await page.goto(origin+'/methodology');await expect.poll(async()=>(await calls()).filter(x=>x[1]==='page_view').length).toBe(1);await page.evaluate(()=>{document.cookie='_ga=fixture; path=/';});await page.getByRole('button',{name:'Keep analytics off',exact:true}).click();await expect(page.getByRole('button',{name:'Keep analytics off',exact:true})).toHaveAttribute('aria-pressed','true');await expect.poll(()=>page.evaluate(()=>document.cookie.includes('_ga='))).toBe(false);const before=(await calls()).filter(x=>x[0]==='event').length;await page.evaluate(()=>window.dispatchEvent(new CustomEvent('bacwater:usage',{detail:'calculation_completed'})));assert.equal((await calls()).filter(x=>x[0]==='event').length,before);});
 await step('Blocked provider transport does not prevent the calculator task',async()=>{await page.goto(origin+'/tools/mg-to-mcg');await page.getByLabel('Milligrams (mg)',{exact:true}).fill('0.125');await expect(page.getByLabel('Micrograms (mcg)',{exact:true})).toHaveValue('125');assert.deepEqual(errors,[]);});
}catch(e){process.exitCode=1;console.error(e);await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});}finally{await prisma.contactMessage.deleteMany({where:{email}});await prisma.$disconnect();await browser.close();await fs.writeFile(out+'/results.json',JSON.stringify({date:new Date().toISOString(),results,errors,requests,mode:'Actual enabled application, local fixtures and intercepted provider transport',limitations:['This verifies application consent, dataLayer contents and actual contact persistence.','Google provider code and GA4 receiving property are not exercised; no actual Google network or account receipt is claimed.','Test-only analytics readiness does not enable production analytics.']},null,2));}
