import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {chromium,firefox,webkit} from '@playwright/test';
const require=createRequire(import.meta.url),origin=process.env.AUDIT_ORIGIN||'https://bacwater.ai',out=process.env.AUDIT_OUT||'audit-evidence/live-baseline',screenshots=process.env.AUDIT_SCREENSHOTS!=='0';
const host=new URL(origin).origin,id=u=>crypto.createHash('sha256').update(u).digest('hex').slice(0,14);
for(const p of ['html','screenshots'])await fs.mkdir(`${out}/${p}`,{recursive:true});
const locations=s=>[...s.matchAll(/<loc>(.*?)<\/loc>/gs)].map(m=>m[1].replace(/&amp;/g,'&'));
async function get(url){const start=Date.now();try{const r=await fetch(url,{signal:AbortSignal.timeout(25000),headers:{'User-Agent':'BACWater-Authorized-Audit/1.0'}}),text=await r.text();return {requested:url,finalUrl:r.url,status:r.status,headers:Object.fromEntries(r.headers),elapsedMs:Date.now()-start,bytes:Buffer.byteLength(text),text};}catch(e){return {requested:url,error:String(e),elapsedMs:Date.now()-start};}}
const discovered=new Map(),queue=[],done=new Set(),pages=[],endpoints=[];
function add(input,source){try{const u=new URL(input,origin);u.hash='';if(u.origin!==host||/^\/(api|admin)\b/.test(u.pathname)||/\.(svg|png|jpe?g|webp|ico|pdf|xml|txt|css|js)$/i.test(u.pathname))return;if(u.pathname.startsWith('/plan/')&&!['/plan/new','/plan/advanced'].includes(u.pathname))return;if(u.search&&!(u.pathname==='/learn'&&[...u.searchParams.keys()].length===1&&(u.searchParams.has('type')||u.searchParams.has('topic')||u.searchParams.has('peptide'))))return;const row=discovered.get(u.href)||{url:u.href,sources:[]};if(!row.sources.includes(source))row.sources.push(source);if(!discovered.has(u.href))queue.push(u.href);discovered.set(u.href,row);}catch{}}
const root=await get(origin+'/sitemap.xml');endpoints.push(root);
if(root.text?.includes('<sitemapindex')){for(const u of locations(root.text)){const r=await get(u);endpoints.push(r);for(const v of locations(r.text||''))add(v,u);}}else for(const u of locations(root.text||''))add(u,'sitemap');
for(const p of ['/','/sitemap','/search','/signin','/signup','/plans','/plans/labels','/plan','/plan/new','/tools','/learn','/peptides'])add(p,'source-route');
while(queue.length&&done.size<250){const batch=queue.splice(0,3).filter(u=>!done.has(u));await Promise.all(batch.map(async u=>{done.add(u);const r=await get(u),htmlFile=`html/${id(u)}.html`;if(r.text)await fs.writeFile(`${out}/${htmlFile}`,r.text);const row={...discovered.get(u),...r,htmlFile};delete row.text;pages.push(row);if(r.headers?.['content-type']?.includes('text/html'))for(const m of r.text.matchAll(/<a\b[^>]*href=["']([^"']+)["']/g))add(m[1].replace(/&amp;/g,'&'),u);}));}
for(const p of ['/robots.txt','/llms.txt','/does-not-exist-audit-20260921','/learn/does-not-exist-audit-20260921','/peptides/does-not-exist-audit-20260921','/peptides/semaglutide/10mg','/tools/ml-to-units','/shop','/cart','/checkout','/plan/advanced','/admin'])endpoints.push(await get(origin+p));
if(origin==='https://bacwater.ai')for(const u of ['http://bacwater.ai/','https://www.bacwater.ai/tools/syringe-units','https://bacwater.ai/tools/bac-water/'])endpoints.push(await get(u));
await fs.writeFile(`${out}/http-inventory.json`,JSON.stringify({date:new Date().toISOString(),origin,pages,endpoints,unvisited:[...discovered.keys()].filter(u=>!done.has(u)),queueRemaining:queue},null,2));
const axe=await fs.readFile(require.resolve('axe-core/axe.min.js'),'utf8');
async function context(browser){const c=await browser.newContext();await c.route(/google-analytics|googletagmanager|clarity\.ms|doubleclick|googlesyndication/,r=>r.abort());await c.addCookies([{name:'bacwater_age_ok',value:'1',url:origin}]);return c;}
async function inspect(c,url,width,engine,accessibility){
 // A separate page avoids attributing aborted prefetches from the previous document
 // to the next URL. Real navigation journeys are tested in the separate suites.
 const page=await c.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));
 try{await page.setViewportSize({width,height:width<768?844:1000});const response=await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(500);await page.waitForLoadState('networkidle',{timeout:5000}).catch(()=>{});
 const data=await page.evaluate(()=>{
 const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};},main=document.querySelector('main')||document.body;
 return {labNavigation:performance.getEntriesByType('navigation').map(n=>({responseStart:n.responseStart,domContentLoaded:n.domContentLoadedEventEnd,load:n.loadEventEnd,transferSize:n.transferSize,encodedBodySize:n.encodedBodySize,decodedBodySize:n.decodedBodySize})),title:document.title,description:document.querySelector('meta[name="description"]')?.content||null,canonical:document.querySelector('link[rel="canonical"]')?.href||null,robots:[...document.querySelectorAll('meta[name="robots"]')].map(e=>e.content),h1:[...document.querySelectorAll('h1')].map(e=>e.textContent),headings:[...main.querySelectorAll('h1,h2,h3,h4')].map(e=>({tag:e.tagName,text:e.textContent})),ids:[...document.querySelectorAll('[id]')].map(e=>e.id),mainText:main.innerText,links:[...document.querySelectorAll('a[href]')].map(e=>({href:e.href,text:e.innerText,...rect(e)})),horizontalOverflow:document.documentElement.scrollWidth>innerWidth+1,overflowElements:[...main.querySelectorAll('*')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.right>innerWidth+2||r.left< -2);}).slice(0,30).map(e=>({tag:e.tagName,class:String(e.className).slice(0,160),text:e.textContent?.slice(0,80),...rect(e)})),images:[...document.images].map(e=>({src:e.currentSrc,alt:e.getAttribute('alt'),loaded:e.complete&&e.naturalWidth>0,...rect(e)})),schema:[...document.querySelectorAll('script[type="application/ld+json"]')].map(e=>{try{return JSON.parse(e.textContent);}catch{return {parseError:true};}}),inputs:[...main.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,type:e.type,label:e.labels?.[0]?.textContent||e.getAttribute('aria-label'),value:e.type==='password'?'[redacted]':e.value,...rect(e)})),forms:[...main.querySelectorAll('form')].map(f=>({inputs:[...f.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,type:e.type,name:e.name,autocomplete:e.autocomplete,label:e.labels?.[0]?.textContent||e.getAttribute('aria-label')}))})),fixed:[...document.querySelectorAll('body *')].filter(e=>['fixed','sticky'].includes(getComputedStyle(e).position)).map(e=>({tag:e.tagName,class:String(e.className).slice(0,100),text:e.textContent?.slice(0,120),...rect(e)}))};
 });let violations=null;if(accessibility){await page.evaluate(axe);const a=await page.evaluate(async()=>window.axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}}));violations=a.violations.map(v=>({id:v.id,impact:v.impact,help:v.help,helpUrl:v.helpUrl,nodes:v.nodes.map(n=>({target:n.target,html:n.html,summary:n.failureSummary}))}));}
 const screenshot=`screenshots/${id(url)}-${engine}-${width}.png`;if(screenshots)await page.screenshot({path:`${out}/${screenshot}`,fullPage:true});return {url,finalUrl:page.url(),width,engine,emulation:'CSS viewport in desktop browser engine, not a physical device',status:response?.status(),errors,...data,violations,screenshot:screenshots?screenshot:null};
 }catch(e){return {url,width,engine,error:String(e),errors};}finally{await page.close();}
}
const b=await chromium.launch(),c=await context(b);const first=await b.newContext({viewport:{width:390,height:844}});await first.route(/google-analytics|googletagmanager|clarity\.ms|doubleclick|googlesyndication/,r=>r.abort());const f=await first.newPage();await f.goto(origin,{waitUntil:'domcontentloaded'});await f.waitForTimeout(700);await f.screenshot({path:`${out}/screenshots/first-visit-390.png`});await first.close();
const targets=pages.filter(p=>p.status===200&&p.headers?.['content-type']?.includes('text/html')),renders=[];let index=0;
await Promise.all([0,1,2].map(async()=>{while(index<targets.length){const item=targets[index++];for(const width of [390,1440])renders.push(await inspect(c,item.url,width,'chromium',width===390));}}));await fs.writeFile(`${out}/rendered-pages.json`,JSON.stringify(renders,null,2));
const templates=['/','/peptide-calculator','/plan/new','/tools/bac-water','/tools/syringe-units','/learn','/learn/bac-water-shelf-life','/peptides/bpc-157','/contact','/tools/vial-labels','/preferred-source','/learn/what-you-cannot-know','/learn?topic=storage','/signup','/recommendations'],responsive=[];
for(const width of [320,375,430,768,1024])for(const route of templates)responsive.push(await inspect(c,origin+route,width,'chromium',false));await b.close();
for(const [name,engine]of[['firefox',firefox],['webkit',webkit]]){let browser;try{browser=await engine.launch();const ctx=await context(browser);for(const route of templates)responsive.push(await inspect(ctx,origin+route,name==='webkit'?390:1440,name,false));}catch(e){responsive.push({engine:name,error:String(e)});}finally{await browser?.close();}}
await fs.writeFile(`${out}/responsive-engines.json`,JSON.stringify(responsive,null,2));
const byUrl=new Map(renders.filter(r=>r.width===390&&!r.error).map(r=>[r.url,r])),fragmentIssues=[];
for(const r of byUrl.values())for(const l of r.links){try{const target=new URL(l.href);if(target.origin!==host||!target.hash||target.hash==='#')continue;const hash=decodeURIComponent(target.hash.slice(1));target.hash='';const dest=byUrl.get(target.href);if(dest&&!dest.ids.includes(hash))fragmentIssues.push({from:r.url,to:l.href,anchor:l.text});}catch{}}
await fs.writeFile(`${out}/fragment-issues.json`,JSON.stringify([...new Map(fragmentIssues.map(x=>[x.from+' '+x.to,x])).values()],null,2));
const summary={date:new Date().toISOString(),origin,httpPages:pages.length,rendered:renders.length,responsive:responsive.length,errors:renders.filter(r=>r.error).length,pagesWithOverflow:renders.filter(r=>r.horizontalOverflow).map(r=>({url:r.url,width:r.width})),violations:renders.filter(r=>r.violations?.length).map(r=>({url:r.url,violations:r.violations.map(v=>({id:v.id,nodes:v.nodes.length}))})),fragmentIssues:fragmentIssues.length,limitations:['Read-only page inventory; controlled write journeys run in separate localhost suites.','Automated tests and browser-engine emulation do not establish WCAG conformance or physical-device compatibility.','Lab timings are not field Core Web Vitals. Screenshots require visual inspection.','Known internal fragment targets are checked. External destination fragments are not certified.']};await fs.writeFile(`${out}/summary.json`,JSON.stringify(summary,null,2));console.log(`Audit captured ${pages.length} HTTP pages, ${renders.length} renders, ${responsive.length} additional checks, ${fragmentIssues.length} fragment findings.`);
