/**
 * Decides whether the last verification run is worth waking someone for.
 *
 * Accumulating links is not the risk; losing them quietly is. A dofollow link
 * that a platform later rewrites to rel="ugc", or a page that is edited or
 * deleted, produces no notification anywhere, and is usually noticed months
 * later if at all. This compares what the register said before this run with
 * what the run read, and writes backlinks/regressions.md when something got
 * worse.
 *
 * Gains are reported too, but only a regression, or a register that contradicts
 * the live web, sets the alert output. Being told about good news daily is how
 * an alert gets ignored.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const DIR = process.env.BACKLINK_DIR || "backlinks";
const RESULT_PATH = path.join(DIR, "verification.json");
const LEDGER_PATH = path.join(DIR, "ledger.json");
const REGRESSION_PATH = path.join(DIR, "regressions.md");

interface Result { id: string; domain: string; placementUrl: string | null; outcome: string; rel: string[]; dofollow: boolean; detail: string }
interface Run { results: Result[]; problems: string[] }
type Status = string;

/** The register as it stood before this run, read from git rather than kept in memory. */
function previousStatuses(): Record<string, Status> {
  try {
    const raw = execFileSync("git", ["show", `HEAD:${LEDGER_PATH}`], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    const ledger = JSON.parse(raw) as { placements: { id: string; status: Status }[] };
    return Object.fromEntries(ledger.placements.map(p => [p.id, p.status]));
  } catch {
    // First run, a shallow checkout, or a renamed file. No baseline means no
    // regression can be asserted, which is the safe direction.
    return {};
  }
}

function setOutput(name: string, value: string): void {
  const file = process.env.GITHUB_OUTPUT;
  if (file) fs.appendFileSync(file, `${name}=${value}\n`);
  console.log(`${name}=${value}`);
}

function main(): void {
  if (!fs.existsSync(RESULT_PATH)) {
    console.log("No verification result to compare; the verify step did not produce one.");
    setOutput("alert", "false");
    return;
  }
  const run = JSON.parse(fs.readFileSync(RESULT_PATH, "utf8")) as Run;
  const before = previousStatuses();
  const after = JSON.parse(fs.readFileSync(LEDGER_PATH, "utf8")) as { placements: { id: string; status: Status }[] };
  const now = Object.fromEntries(after.placements.map(p => [p.id, p.status]));

  const lost: string[] = [], weakened: string[] = [], gained: string[] = [];
  for (const result of run.results) {
    const was = before[result.id], is = now[result.id];
    if (!was || was === is) continue;
    const link = result.placementUrl ? `[${result.domain}](${result.placementUrl})` : result.domain;
    if (was === "live" && is === "live-nofollow") weakened.push(`- ${link} was dofollow and is now \`rel="${result.rel.join(" ") || "page-level nofollow"}"\`.`);
    else if (was === "live" && is === "rejected") lost.push(`- ${link} was a dofollow link and the page no longer carries it. ${result.detail}`);
    else if (was === "live-nofollow" && is === "rejected") lost.push(`- ${link} was a live nofollow link and the page no longer carries it. ${result.detail}`);
    else if (is === "live" && was !== "live") gained.push(`- ${link} is now a verified dofollow link.`);
  }

  const alert = lost.length > 0 || weakened.length > 0 || run.problems.length > 0 || process.env.VERIFY_OUTCOME === "failure";
  if (!alert) {
    fs.rmSync(REGRESSION_PATH, { force: true });
    console.log(`Nothing to raise.${gained.length ? ` ${gained.length} placement(s) improved.` : ""}`);
    setOutput("alert", "false");
    return;
  }

  const lines = [`Automated check on ${new Date().toISOString().slice(0, 10)} found something that needs a look.`, ""];
  if (lost.length) lines.push("## Links that disappeared", "", ...lost, "");
  if (weakened.length) lines.push("## Links that stopped passing equity", "", ...weakened, "");
  if (run.problems.length) lines.push("## The register disagrees with the live web", "", ...run.problems.map(p => `- ${p}`), "");
  if (process.env.VERIFY_OUTCOME === "failure" && !run.problems.length) lines.push("The verification step exited non-zero. See the workflow log.", "");
  if (gained.length) lines.push("## Also, for context", "", ...gained, "");
  lines.push("---", "", "Raised by `.github/workflows/backlinks.yml`. The full report is `backlinks/verification-report.md` on main.", "",
    "_Generated by [Claude Code](https://claude.ai/code)_");
  fs.writeFileSync(REGRESSION_PATH, lines.join("\n"));
  console.log(`Raising an issue: ${lost.length} lost, ${weakened.length} weakened, ${run.problems.length} register problem(s).`);
  setOutput("alert", "true");
}

main();
