import assert from "node:assert/strict";
import fs from "node:fs";
import { SUPPLIER_PRODUCTS, getSupplierCatalog, productForReference, productCalculatorPath, productForCalculatorPath } from "../src/lib/partners/supplier-catalog";
import { emptyProductValues, readProductValues, productCalculation, numberLabel } from "../src/lib/partners/product-calculation";
import { isCalculatorWorkspace } from "../src/lib/calculator-routes";
const byId=(id:string)=>SUPPLIER_PRODUCTS.find(p=>p.id===id)!;
let checks=0;const test=(name:string,fn:()=>void)=>{fn();checks++;console.log('PASS '+name);};
test("50 distinct reviewed individual listings",()=>{assert.equal(SUPPLIER_PRODUCTS.length,50);assert.equal(new Set(SUPPLIER_PRODUCTS.map(p=>p.id)).size,50);});
test("all listings have exact product links and focused calculation routes",()=>{for(const p of SUPPLIER_PRODUCTS){assert.equal(p.sourceUrl,`https://www.aminoclub.com/us/products/${p.id}`);assert.ok(isCalculatorWorkspace(productCalculatorPath(p.id)));assert.equal(productForCalculatorPath(productCalculatorPath(p.id))?.id,p.id);assert.ok(p.mark&&p.name);}});
test("featured order retained without excluding the rest of the store",()=>assert.deepEqual(SUPPLIER_PRODUCTS.slice(0,7).map(p=>p.id),['amino-h2o','glp-1','glp-2','glp-3','bpc-157','ghk-cu','tb-500']));
test("exact partner product names are allowed without impersonating the supplier",()=>{assert.equal(byId('amino-h2o').name,'Amino H2O');assert.equal(byId('glp-3').name,'GLP-3 (RT)');for(const path of ['src/components/partners/supplier-recommendations.tsx','src/components/partners/product-quick-view.tsx','src/app/recommendations/page.tsx'])assert.doesNotMatch(fs.readFileSync(path,'utf8'),/official Amino Club|authorized spokesperson|approved by Amino Club/i);});
test("mapping is exact and does not substitute a related compound or spray",()=>{assert.equal(productForReference('semaglutide')?.id,'glp-1');assert.equal(productForReference('tirzepatide')?.id,'glp-2');assert.equal(productForReference('retatrutide')?.id,'glp-3');assert.equal(productForReference('cjc-1295-no-dac'),undefined);assert.equal(productForReference('hcg'),undefined);assert.equal(productForReference('ghk-cu')?.kind,'single');assert.equal(byId('ghkcu-spray').kind,'spray');});
test("no supplier media or live prices imported",()=>{const source=fs.readFileSync('src/components/partners/product-artwork.tsx','utf8');assert.ok(source.includes('<svg'));assert.doesNotMatch(source,/<image|https?:|price|purity|99%/i);assert.ok(SUPPLIER_PRODUCTS.every(p=>!('price' in p)&&!('imageUrl' in p)));});
test("plain links do not invent partner approval",()=>{const c=getSupplierCatalog({});assert.equal(c.length,50);assert.ok(c.every(p=>p.href===p.sourceUrl&&!p.paid));});
test("every calculator starts with no numeric inputs or guessed result",()=>{for(const p of SUPPLIER_PRODUCTS)assert.equal(productCalculation(p,emptyProductValues()).ready,false);});
test("single compound uses independently entered mass and final volume",()=>{const r=productCalculation(byId('pinealon'),{...emptyProductValues(),total:'12',volume:'4',amount:'600'});assert.ok(r.ready);assert.deepEqual(r.lines,['3 mg/mL','0.2 mL = 20 U-100 scale units']);});
test("invalid and oversized mass values cannot produce a result",()=>{for(const s of ['','0','-2','Infinity','NaN','0x10','1e999','12mg'])assert.equal(productCalculation(byId('pinealon'),{...emptyProductValues(),total:s,volume:'4',amount:'600'}).ready,false);assert.equal(productCalculation(byId('pinealon'),{...emptyProductValues(),total:'1',volume:'4',amount:'2000'}).ready,false);});
test("a blend uses each entered ingredient, not a guessed equal ratio",()=>{const r=productCalculation(byId('glow'),{...emptyProductValues(),blendMode:'ingredients',volume:'2',amount:'0.2',ingredients:[{name:'BPC-157',mass:'10'},{name:'TB-500',mass:'4'},{name:'GHK-Cu',mass:'6'}]});assert.ok(r.ready);assert.deepEqual(r.lines,['BPC-157: 5 mg/mL; 1 mg in your sample','TB-500: 2 mg/mL; 0.4 mg in your sample','GHK-Cu: 3 mg/mL; 0.6 mg in your sample']);});
test("incomplete blends or too-large samples are rejected",()=>{assert.equal(productCalculation(byId('klow'),{...emptyProductValues(),volume:'2',amount:'0.2'}).ready,false);assert.equal(productCalculation(byId('klow'),{...emptyProductValues(),volume:'2',amount:'3',ingredients:[{name:'A',mass:'10'},{name:'B',mass:'4'}]}).ready,false);});
test("sprays use known solution concentration without reconstitution or syringe output",()=>{const r=productCalculation(byId('nad-plus-spray'),{...emptyProductValues(),total:'25',amount:'0.2'});assert.ok(r.ready);assert.equal(r.text,'5 mg (5000 mcg) in 0.2 mL');assert.doesNotMatch(r.text,/U-100|water|sprays/i);});
test("blend spray requires the specific ingredient",()=>{const v={...emptyProductValues(),blendMode:"ingredients" as const,total:'25',amount:'0.2'};assert.equal(productCalculation(byId('bpc-tb-spray'),v).ready,false);assert.ok(productCalculation(byId('bpc-tb-spray'),{...v,ingredient:'BPC-157'}).text.startsWith('BPC-157:'));});
test("water counts only entered volumes",()=>{const v={...emptyProductValues(),volume:'2',count:'7',total:'10'};assert.deepEqual(productCalculation(byId('amino-h2o'),v).lines,['14 mL total','2 bottles by volume, before any loss']);assert.equal(productCalculation(byId('amino-h2o'),{...v,count:'1.5'}).ready,false);assert.equal(productCalculation(byId('amino-h2o'),{...v,total:'1e-12',volume:'1e12'}).ready,false);});
test("storage corruption fails safely",()=>{for(const raw of [null,[],{},'broken',{ingredients:[null,'string']},{total:12,amount:Infinity}])assert.equal(productCalculation(byId('pinealon'),readProductValues(raw)).ready,false);});
test("very small positive results do not display as zero",()=>{assert.notEqual(numberLabel(1e-24),'0');assert.match(numberLabel(1e-24),/e-24/);});


test("every known blend requires all its named components",()=>{for(const id of ["glow","klow","cjc-ipa-no-dac","wolverine-stack"]){const p=byId(id),v={...emptyProductValues(p),blendMode:"ingredients" as const,volume:"2",amount:"0.2"};v.ingredients=v.ingredients.map(row=>({...row,mass:"4"}));assert.equal(productCalculation(p,v).ready,true,id);assert.equal(productCalculation(p,{...v,ingredients:v.ingredients.slice(1)}).ready,false,id);assert.equal(productCalculation(p,{...v,ingredients:v.ingredients.map((row,i)=>i?row:{...row,name:"unknown"})}).ready,false,id);}});
test("legacy blend values never move to another ingredient",()=>{const p=byId("glow");const r=readProductValues({ingredients:[{name:"GHK-Cu",mass:"6"},{name:"BPC-157",mass:"10"}]},p);assert.deepEqual(r.ingredients,[{name:"BPC-157",mass:"10"},{name:"TB-500",mass:""},{name:"GHK-Cu",mass:"6"}]);assert.equal(productCalculation(p,{...r,blendMode:"ingredients",volume:"2",amount:"0.2"}).ready,false);assert.ok(readProductValues({ingredients:[{name:"A",mass:"10"},{name:"B",mass:"4"}]},p).ingredients.every(row=>row.mass===""));});

test("premixed blends calculate a combined concentration without inventing ratios",()=>{const p=byId("glow"),v={...emptyProductValues(p),total:"12",volume:"4"};assert.deepEqual(productCalculation(p,v).lines,["3 mg/mL total blend concentration","This is the combined mass. Individual ingredient amounts cannot be determined from the total alone."]);assert.equal(productCalculation(p,{...v,amount:"0.2"}).lines[1],"0.6 mg total blend in 0.2 mL");assert.equal(productCalculation(p,{...v,amount:"0"}).ready,false);assert.equal(productCalculation(p,{...v,amount:"5"}).ready,false);assert.equal(productCalculation(p,{...v,blendMode:"ingredients"}).ready,false);});

test("all premixed powder blends and the blend solution support total-only math",()=>{for(const id of ["glow","klow","cjc-ipa-no-dac","wolverine-stack"]){const p=byId(id);assert.equal(productCalculation(p,{...emptyProductValues(p),total:"12",volume:"4"}).lines[0],"3 mg/mL total blend concentration",id);}const p=byId("bpc-tb-spray");const r=productCalculation(p,{...emptyProductValues(p),total:"3",amount:"0.2",ingredient:"Ignored stale ingredient"});assert.equal(r.ready,true);assert.equal(r.lines[0],"Total blend: 0.6 mg (600 mcg) in 0.2 mL");assert.doesNotMatch(r.text,/Ignored|U-100/);});

console.log(`${checks} catalog and product-calculation groups passed.`);
