import assert from "node:assert/strict";
import fs from "node:fs";
import { resolveAmountSchedule, switchAmountBasis, switchAmountUnit, frequencyCount } from "../src/lib/calc/amount-schedule";
import { EMPTY_MASS, parseCalculatorSession, massText } from "../src/lib/calculator-session";
import { calculate } from "../src/lib/calc";
let count = 0;
const test = (name: string, fn: () => void) => { fn(); count++; console.log(`PASS session/schedule: ${name}`); };
const each = { ...EMPTY_MASS, amount: "0.4", frequency: "2" };
test("each-time input is multiplied for the week, not divided twice", () => { const s = resolveAmountSchedule(each); assert.ok(s.ready); assert.equal(s.eachMcg, 400); assert.equal(s.weeklyMcg, 800); const r = calculate({ vialStrengthMg: 40, bacWaterMl: 2, doseMcg: s.normalizedTotalMcg, injectionsPerWeek: s.count!, syringeType: "insulin-1ml" }); assert.equal(r.doseVolumeMl, 0.02); });
test("weekly input is divided across the explicit count", () => { const s = resolveAmountSchedule({ ...each, basis: "week" }); assert.equal(s.eachMcg, 200); assert.equal(s.weeklyMcg, 400); });
test("daily frequency means seven unchanged each-time amounts", () => { const s = resolveAmountSchedule({ ...each, frequency: "7" }); assert.equal(s.eachMcg, 400); assert.equal(s.weeklyMcg, 2800); });
test("twice daily means fourteen, without selecting an amount", () => { assert.equal(resolveAmountSchedule({ ...each, frequency: "14" }).weeklyMcg, 5600); assert.equal(resolveAmountSchedule({ ...EMPTY_MASS, frequency: "14" }).ready, false); });
test("no entered schedule does not invent one", () => { const s = resolveAmountSchedule({ ...each, frequency: "" }); assert.equal(s.eachMcg, 400); assert.equal(s.weeklyMcg, null); assert.equal(s.count, null); });
test("weekly total needs an explicit frequency", () => assert.equal(resolveAmountSchedule({ ...each, basis: "week", frequency: "" }).ready, false));
test("changing basis with a known count preserves each-time mass", () => { const s = switchAmountBasis(each, "week"); assert.equal(s.amount, "0.8"); assert.equal(resolveAmountSchedule(s).eachMcg, 400); assert.equal(switchAmountBasis(s, "each").amount, "0.4"); });
test("unknown time basis is not silently reinterpreted", () => assert.equal(switchAmountBasis({ ...each, frequency: "" }, "week").amount, ""));
test("unit changes preserve mass including incomplete invalid inputs", () => { const s = switchAmountUnit(each, "mcg"); assert.equal(s.amount, "400"); assert.equal(resolveAmountSchedule(s).eachMcg, 400); assert.equal(switchAmountUnit({ ...each, amount: "1,000" }, "mcg").amount, "1,000"); });
test("backend and UI use the same finite whole-count limit", () => { for (const n of ["0", "-1", "1.5", "29", "Infinity", "NaN", "1e1"]) assert.equal(frequencyCount(n), null); assert.equal(frequencyCount("28"), 28); });
test("invalid amount or schedule never produces an each-time result", () => { for (const amount of ["", "0", "-1", "1,000", "4mg", "Infinity", "1e999"]) assert.equal(resolveAmountSchedule({ ...each, amount }).ready, false); });
test("same unit values retain raw decimal text", () => { assert.equal(massText("0.", "mg", "mg"), "0."); assert.equal(massText("400", "mcg", "mg"), "0.4"); });
test("fresh sessions are empty and versioned", () => { for (const text of [null, "{", "[]", '{"version":0}', "x".repeat(65537)]) assert.equal(parseCalculatorSession(text).mass, EMPTY_MASS); });
test("malformed and oversized fields cannot become a cross-tool draft", () => { const s = parseCalculatorSession(JSON.stringify({ version: 1, mass: { total: 12, volume: {}, amount: "x".repeat(65), amountUnit: "IU", totalUnit: "IU", step: 99, syringe: "other" }, tools: { "__proto__": {}, "not/a/key": "bad" } })); assert.equal(s.mass.total, ""); assert.equal(s.mass.amount, ""); assert.equal(s.mass.amountUnit, "mg"); assert.equal(s.mass.step, 0); assert.deepEqual(s.tools, {}); });
test("saved session preserves the original amount basis and named product", () => { const draft = { ...each, total: "40", volume: "2", productId: "glp-3", peptideSlug: "retatrutide", step: 2 }; assert.deepEqual(parseCalculatorSession(JSON.stringify({ version: 1, mass: draft, tools: {} })).mass, draft); });
test("session module cannot send calculator entries to a server", () => { const source = fs.readFileSync("src/lib/calculator-session.ts", "utf8"); assert.ok(source.includes("window.sessionStorage")); assert.equal(/\bfetch\(|sendBeacon|gtag\(|localStorage/.test(source), false); });
console.log(`${count} session and amount/schedule groups passed.`);
