import assert from "node:assert/strict";
import fs from "node:fs";
import { addLabelDays, labelUseBy, labelLayout, mmToPt, validMixDate, validLabelSize, DEFAULT_LABEL_SIZE } from "../src/lib/labels/layout";
let count=0;const test=(name:string,run:()=>void)=>{run();count++;console.log(`PASS labels: ${name}`);};
test("mix date alone never invents an expiry",()=>assert.equal(labelUseBy("2026-09-01","").date,""));
test("date updates automatically from the entered whole-day period",()=>{assert.equal(labelUseBy("2026-09-01","10").date,"2026-09-11");assert.equal(labelUseBy("2026-09-03","10").date,"2026-09-13");});
test("original printed expiry caps the computed use-by date",()=>{assert.equal(labelUseBy("2026-09-01","10","2026-09-05").date,"2026-09-05");assert.equal(labelUseBy("2026-09-01","10","2026-10-05").date,"2026-09-11");});
test("printed expiry before mixing is rejected",()=>assert.equal(labelUseBy("2026-09-01","10","2026-08-31").kind,"error"));
test("leap days and month boundaries are calendar arithmetic",()=>{assert.equal(addLabelDays("2028-02-28",2),"2028-03-01");assert.equal(addLabelDays("2026-12-31",1),"2027-01-01");});
test("impossible dates never roll over silently",()=>{for(const v of ["2026-02-29","2026-02-30","2026-13-01","2026-09-00","hello",""])assert.equal(validMixDate(v),false);});
test("dates do not change with timezone or daylight saving",()=>{const old=process.env.TZ;for(const zone of ["Pacific/Kiritimati","Pacific/Pago_Pago","America/Denver","UTC"]){process.env.TZ=zone;assert.equal(addLabelDays("2026-03-07",3),"2026-03-10");}if(old)process.env.TZ=old;else delete process.env.TZ;});
test("invalid and sub-day periods cannot create a plausible expiry",()=>{for(const v of ["0","-1","1.5","1e2","NaN","Infinity","3651","20 days"])assert.equal(labelUseBy("2026-09-01",v).kind,"error");});
test("default dimensions are thirty by fifteen millimeters",()=>{assert.deepEqual(DEFAULT_LABEL_SIZE,{width:30,height:15});assert.ok(Math.abs(mmToPt(30)-85.03937)<.001);});
test("label-printer PDF pages match the selected label exactly",()=>{const p=labelLayout({width:25,height:13},"label");assert.equal(p.pageWidth,25);assert.equal(p.pageHeight,13);assert.equal(p.perPage,1);assert.equal(p.margin,0);});
test("paper layouts retain physical label dimensions with real margins",()=>{const p=labelLayout(DEFAULT_LABEL_SIZE,"letter");assert.equal(p.pageWidth,215.9);assert.equal(p.pageHeight,279.4);assert.equal(p.columns,6);assert.ok(p.perPage>=30);});
test("invalid custom paper dimensions are rejected",()=>{for(const size of [{width:0,height:15},{width:100,height:15},{width:30,height:5},{width:NaN,height:20}])assert.equal(validLabelSize(size),false);});
test("labels do not revive legacy shelf days or prescribe a dose",()=>{const s=fs.readFileSync("src/components/plan/vial-label.tsx","utf8");assert.equal(s.includes("data.shelfDays"),false);assert.equal(s.includes("/dose"),false);assert.equal(s.includes("mL BAC"),false);assert.ok(s.includes("NOT SET"));});
test("print CSS overrides enlarged preview scale",()=>{const s=fs.readFileSync("src/components/plan/vial-label.tsx","utf8");assert.ok(s.includes("--preview-scale:1!important"));assert.ok(s.includes("break-inside:avoid"));assert.equal(s.includes("2.5in"),false);});
console.log(`${count} date-safety and physical label-layout checks passed.`);
