import assert from "node:assert/strict";
import fs from "node:fs";
import { SUPPLIER_PRODUCTS, getSupplierCatalog } from "../src/lib/partners/supplier-catalog";
const expected=["amino-h2o","glp-1","glp-2","glp-3","bpc-157","ghk-cu","tb-500"];
const plain=getSupplierCatalog({});
assert.deepEqual(plain.slice(0,7).map(p=>p.id),expected);
assert.ok(plain.every(p=>!p.paid&&p.href===p.sourceUrl&&new URL(p.href).search===""));
const first=plain[0];
const linked=getSupplierCatalog({AMINO_CLUB_ENABLED:"true",AMINO_CLUB_APPROVAL_AND_LINKS_VERIFIED:"true",AMINO_CLUB_PRODUCT_LINKS_JSON:JSON.stringify({"amino-h2o":first.sourceUrl+"?ref=TEST_ONLY"})});
assert.equal(linked.length,50);assert.ok(linked[0].paid);assert.ok(linked.slice(1).every(p=>!p.paid));
const pending=getSupplierCatalog({AMINO_CLUB_ENABLED:"true",AMINO_CLUB_APPROVAL_AND_LINKS_VERIFIED:"false",AMINO_CLUB_PRODUCT_LINKS_JSON:JSON.stringify({"amino-h2o":first.sourceUrl+"?ref=TEST_ONLY"})});
assert.deepEqual(pending,plain);
assert.deepEqual(getSupplierCatalog({AMINO_CLUB_ENABLED:"true",AMINO_CLUB_APPROVAL_AND_LINKS_VERIFIED:"true",AMINO_CLUB_PRODUCT_LINKS_JSON:'{"amino-h2o":"https://bad.example"}'}),plain);
for(const p of SUPPLIER_PRODUCTS)assert.match(p.sourceUrl,/^https:\/\/www\.aminoclub\.com\/us\/products\/[a-z0-9-]+$/);
assert.equal(SUPPLIER_PRODUCTS.find(p=>p.name==="Tirzepatide")?.id,"glp-2");assert.equal(SUPPLIER_PRODUCTS.find(p=>p.name==="Retatrutide")?.id,"glp-3");
for(const path of ["src/components/layout/site-header.tsx","src/components/layout/site-footer.tsx","src/app/admin/layout.tsx"])assert.ok(fs.readFileSync(path,"utf8").includes("<Wordmark"),path);
for(const file of ["bacwater-wordmark.svg","bacwater-wordmark-light.svg","bacwater-mark.svg"]){const s=fs.readFileSync("public/brand/"+file,"utf8");assert.ok(s.startsWith("<svg"));assert.equal(/https?:|<script|<image|@font-face/.test(s.replace('xmlns="http://www.w3.org/2000/svg"',"")),false);}
const slider=fs.readFileSync("src/components/partners/product-slider.tsx","utf8");assert.ok(slider.includes('filtered.map('));assert.equal(slider.includes('setInterval'),false);assert.ok(slider.includes('prefers-reduced-motion'));
assert.ok(fs.readFileSync("src/lib/seo/sitemap.ts","utf8").includes('path:"/recommendations"'));
assert.equal(fs.readFileSync("src/lib/positioning.ts","utf8").includes("recommends no vendor"),false);
console.log("PASS 50 fixed listings, public fallback, verified paid links, product identities, shared wordmark, manual carousel and discovery boundaries.");
