import assert from "node:assert/strict";
import fs from "node:fs";
import { BASE_SEARCH_ITEMS, searchItems, productChoices, referenceArtwork } from "../src/lib/search/public-index";
import { SUPPLIER_PRODUCTS } from "../src/lib/partners/supplier-catalog";
import { searchScore } from "../src/lib/search/matching";
let count=0;const test=(name:string,run:()=>void)=>{run();count++;console.log(`PASS search: ${name}`);};
test("all 50 supplier listings have real internal calculator destinations",()=>{const p=BASE_SEARCH_ITEMS.filter(i=>i.kind==="product");assert.equal(p.length,50);assert.ok(p.every(i=>i.href.startsWith("/calculate/product/")));});
test("normalization handles case, spacing and punctuation",()=>{assert.ok(searchScore("bpc157","BPC-157")>0);assert.ok(searchScore("ghk cu","GHK-Cu")>0);assert.ok(searchScore("tirzepetide","Tirzepatide")>0);});
test("broad peptide synonyms still require choosing the exact product",()=>{assert.equal(searchItems(BASE_SEARCH_ITEMS,"glp 1")[0]?.productId,"glp-1");assert.ok(searchItems(BASE_SEARCH_ITEMS,"cjc1295 with dac").some(i=>i.reference==="cjc-1295-with-dac"));});
test("a beginner question can find the unit glossary",()=>assert.equal(searchItems(BASE_SEARCH_ITEMS,"what does mcg mean?")[0]?.href,"/learn/glossary"));
test("a buying query can reach the water listing",()=>assert.ok(searchItems(BASE_SEARCH_ITEMS,"where can I buy BAC water").some(i=>i.productId===SUPPLIER_PRODUCTS[0].id)));
test("category filters never mix result types",()=>assert.ok(searchItems(BASE_SEARCH_ITEMS,"water","product").every(i=>i.kind==="product")));
test("no-match text produces no invented result",()=>assert.equal(searchItems(BASE_SEARCH_ITEMS,"zzzz-no-such-thing-94727").length,0));
test("default search contains no admin, notes, edit or private account routes",()=>assert.ok(BASE_SEARCH_ITEMS.every(i=>!/^\/(admin|plans|plan\/|api|account|settings)/.test(i.href))));
test("product picker keeps every listed product and all extra references",()=>{const choices=productChoices();for(const p of SUPPLIER_PRODUCTS)assert.ok(choices.some(c=>c.product?.id===p.id),p.id);assert.ok(choices.some(c=>c.value==="hcg"));assert.ok(choices.some(c=>c.value==="custom"));});
test("reference-only mass picker does not offer hCG IU",()=>assert.equal(productChoices(true).some(c=>c.value==="hcg"),false));
test("unknown reference does not invent a product or link",()=>{assert.equal(referenceArtwork("not-a-real-product"),undefined);assert.equal(referenceArtwork("hcg")?.sourceUrl,"");});
test("search endpoint reads published catalog and never accepts private query input",()=>{const s=fs.readFileSync("src/app/api/search-index/route.ts","utf8");assert.ok(s.includes("getCatalog(true)"));assert.equal(/searchParams|request\.json|request\.text/.test(s),false);assert.ok(s.includes('"private, no-store"'));});
test("search text is not sent as an API query or analytics event",()=>{const s=fs.readFileSync("src/components/search/site-search.tsx","utf8");assert.ok(s.includes('fetch("/api/search-index"'));assert.equal(/gtag|dataLayer|sendBeacon|fetch\([^\n]*query/.test(s),false);});
test("beginner labels distinguish total liquid from water added",()=>{const s=fs.readFileSync("src/components/plan/plan-results.tsx","utf8");assert.ok(s.includes("not instructions to add that much water"));assert.equal(s.includes("swirl gently"),false);const pdf=fs.readFileSync("src/components/plan/plan-pdf.tsx","utf8");assert.ok(pdf.includes("TOTAL LIQUID VOLUME"));assert.equal(pdf.includes("BAC WATER ADDED"),false);});
console.log(`${count} search, product coverage and clarity checks passed.`);
