import assert from "node:assert/strict";
import "./test-unit-switching";
import fs from "node:fs";
import { calculate, type CalcInput } from "../src/lib/calc";
import { planPreviewState, type PlanPreviewInput } from "../src/lib/calc/plan-preview";
const input: CalcInput = {peptideSlug:"bpc-157",peptideName:"BPC-157",vialStrengthMg:12,doseMcg:300,injectionsPerWeek:1,bacWaterMl:4,syringeType:"insulin-1ml",dateMixed:null};
const base: PlanPreviewInput = {input,result:calculate(input),hasProduct:true,vialText:"12",vialUnit:"mg",volumeText:"4",amount:{amount:"0.3",amountUnit:"mg",basis:"each",timesPerWeek:""},secondaryReady:true,hydrated:true};
const preview=planPreviewState(base);
assert.equal(preview.ready,true);
for(const changes of [{hasProduct:false},{vialText:"0"},{volumeText:"0"},{hydrated:false},{secondaryReady:false},{amount:{...base.amount,amount:"-1"}}])assert.equal(planPreviewState({...base,...changes}).ready,false);
assert.ok(Math.abs(base.result.doseVolumeMl - 0.1) < 1e-12);
const weekly={...base,input:{...input,doseMcg:600,injectionsPerWeek:2},amount:{amount:"0.6",amountUnit:"mg" as const,basis:"week" as const,timesPerWeek:"2"}};
const week=planPreviewState({...weekly,result:calculate(weekly.input)});assert.equal(week.ready,true);assert.ok(Math.abs(calculate(weekly.input).doseVolumeMl - 0.1) < 1e-12);
const iu=planPreviewState({...base,input:{...input,peptideSlug:"hcg"}});assert.equal(iu.ready,false);
const hero=fs.readFileSync("src/components/brand/hero-calculator.tsx","utf8"),form=fs.readFileSync("src/components/plan/plan-form.tsx","utf8"),view=fs.readFileSync("src/components/brand/hero-plan-steps.tsx","utf8");
assert.match(hero,/<GuidedPlan mode="beginner" presentation="hero"/);
assert.match(hero,/!open \? content\("inline"\)/);
assert.match(form,/onSave=\{handleSave\}/);
assert.doesNotMatch(view,/fetch\(|sendBeacon|dataLayer|gtag\(/);
assert.match(view,/p\.onClear\(\)/);
console.log("PASS guided hero: product-first prerequisites, restored draft bounds, invalid input gating, shared math, schedule meaning, save action and privacy.");

// Conditional questions keep their identity, and invalid earlier inputs hide a restored result.
import { questionIndex } from "../src/lib/calc/question-steps";
const questions = [{id:"product",complete:true},{id:"amount",complete:true},{id:"custom-schedule",complete:false},{id:"review",complete:false}];
assert.equal(questionIndex("review",questions),2);
assert.equal(questionIndex("amount",questions),1);
assert.equal(questionIndex("missing",questions),0);
assert.equal(questionIndex("review",questions.filter(q=>q.id!=="custom-schedule")),2);
assert.equal(questionIndex("review",questions.map(q=>({...q,complete:true}))),3);
assert.equal(questionIndex("review",questions.map(q=>({...q,complete:q.id!=="amount"}))),1);
console.log("PASS one-question navigation: conditional identity, Back, invalidation and restored result guards.");
