import Link from "next/link";
export const metadata = { title: "Privacy and Data Use", description: "How BACwater.ai handles accounts, saved calculation plans, support messages and optional analytics.", alternates: { canonical: "/privacy" } };
export default function PrivacyPage() { return <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6 space-y-6"><h1 className="text-4xl font-serif">Privacy and data use</h1><p>Updated September 24, 2026. BACwater.ai is a free calculation and reference site, not a medical service or an online shop.</p>
<h2 className="text-2xl font-serif">Accounts and saved plans</h2><p>Creating an account stores your name, email address and a password hash, or the account information supplied by your sign-in provider. Saving a plan sends its calculation inputs and results to our database. Notes and custom plan names are available only to the owning account or the anonymous device holding the plan&apos;s creation secret.</p>
<h2 className="text-2xl font-serif">Shared links</h2><p>Anyone with a saved plan&apos;s share link can read its calculation, label or public PDF. The link is not a private document vault. Private notes are omitted from a shared viewer&apos;s PDF. Do not put personal or health information in compound names or calculation fields.</p>
<h2 className="text-2xl font-serif">Device storage</h2><p>Essential cookies keep you signed in, remember age confirmation, and prove ownership of anonymous plans. Local or session storage may keep your draft, saved-plan list, anonymous claim secrets and preferences. Clearing browser data can remove access to anonymous plans. Sign in and claim plans before clearing it.</p>
<h2 className="text-2xl font-serif">Support and optional AI explanations</h2><p>Support submissions are stored in the administrative inbox. When staff send a reply through the configured email provider, the provider processes the recipient address and message. Built-in explanations validate the submitted numeric inputs on our server and do not send them to an AI provider. If optional AI question routing is enabled, requires sign-in, and you expressly allow it, only the latest question is sent to the configured provider to select a fixed topic. Names, notes, calculation context and earlier messages are not included. Replies use built-in explanations, not model-generated advice. Do not submit health records or other sensitive information.</p>
<h2 className="text-2xl font-serif">Analytics and session replay</h2><p>Optional analytics are off by default and require both verified configuration and your consent. The controls at the bottom of this page let you decline or withdraw consent. Where enabled, only approved usage events and broad public page categories are sent, not plan identifiers, notes, input values or full query strings. Session replay is not loaded by this release. Rejecting optional tracking does not prevent calculations or saving plans.</p>
<h2 className="text-2xl font-serif">External research-supplier links</h2><p>Product links may contain our public affiliate code and campaign source. We may earn a commission from qualifying purchases through those links. These fields identify our referral relationship, not you. We do not append calculator values, plan identifiers, notes, email addresses, directory search text or query strings from your visit. No supplier tracking script or external product image is loaded by this integration. Clicking a link opens the supplier site, whose own privacy and attribution policies then apply. A commission disclosure appears beside paid links.</p>
<h2 className="text-2xl font-serif">Product directory search</h2><p>The directory matches product names and formats locally in your browser. It does not send your search text to an AI provider or supplier, add it to a page URL, or save it as a product preference. It does not use health information, account details or saved calculation plans to rank products.</p>
<h2 className="text-2xl font-serif">Service providers and retention</h2><p>Hosting, database, authentication, configured email delivery and optional AI services process the information needed for those functions. Saved records remain until deleted through supported controls or handled through a verified support request. Backup retention and any legally required retention need to be considered separately; this page does not promise immediate removal from every backup.</p>
<h2 className="text-2xl font-serif">Questions and requests</h2><p>Use the <Link className="underline" href="/contact">contact form</Link> to ask about access, correction or deletion. We may need to verify ownership before changing or disclosing account data. Do not send a password. The rights and retention obligations that apply can depend on your location and the circumstances.</p><Link className="underline" href="/">Back to BACwater.ai</Link></article>; }
