import { withSocialMetadata } from "@/lib/seo/social-metadata";
import Link from "next/link";
export const metadata = withSocialMetadata({ title: "Privacy and Data Use", description: "How BACwater.ai handles accounts, saved calculation plans, support messages and optional analytics.", alternates: { canonical: "/privacy" } });
export default function PrivacyPage() { return <article className="mx-auto max-w-3xl px-4 py-12 sm:px-6 space-y-6"><h1 className="text-4xl font-serif">Privacy and data use</h1><p>Updated September 28, 2026. BACwater.ai is a free calculation and reference site, not a medical service or an online shop.</p>
<h2 className="text-2xl font-serif">Accounts and saved plans</h2><p>Creating an account stores your name, email address and a password hash, or the account information supplied by your sign-in provider. Saving a plan sends its calculation inputs and results to our database. Notes and custom plan names are available only to the owning account or the anonymous device holding the plan&apos;s creation secret.</p>
<h2 className="text-2xl font-serif">Abuse prevention</h2><p>Sign-in, registration, password recovery and support forms use temporary request counters to limit repeated attempts. Account-specific counters use a keyed hash of your email address instead of storing the address in the counter. They do not contain your password, IP address or message. Expired counters are removed as later requests are processed.</p>
<h2 className="text-2xl font-serif">Password recovery</h2><p>A requested reset email is delivered through our configured email provider. We store only a hash of the single-use reset token, with a 30-minute expiry. Resetting the password revokes existing account sessions. Reset links and account identifiers are excluded from optional analytics.</p>
<h2 className="text-2xl font-serif">Shared links</h2><p>Anyone with a saved plan&apos;s share link can read its calculation, label or public PDF. The link is not a private document vault. Private notes are omitted from a shared viewer&apos;s PDF. Do not put personal or health information in compound names or calculation fields.</p>
<h2 className="text-2xl font-serif">Embedded converter</h2><p>Our free embedded mass converter runs in the host page without sending input values to BACwater.ai. It does not set cookies, save entries or load analytics. Loading its script makes an ordinary server request; the hosting provider may process standard request information. The website embedding it may have its own tracking, which is governed by that website&apos;s practices.</p>
<h2 className="text-2xl font-serif">Device storage</h2><p>Essential cookies keep you signed in, remember age confirmation, and prove ownership of anonymous plans. Local or session storage may keep your draft, saved-plan list, anonymous claim secrets and preferences. Clearing browser data can remove access to anonymous plans. Sign in and claim plans before clearing it.</p>
<h2 className="text-2xl font-serif">Support and optional AI explanations</h2><p>Support submissions are stored in the administrative inbox. When staff send a reply through the configured email provider, the provider processes the recipient address and message. Built-in explanations validate the submitted numeric inputs on our server and do not send them to an AI provider. If optional AI question routing is enabled, requires sign-in, and you expressly allow it, only the latest question is sent to the configured provider to select a fixed topic. Names, notes, calculation context and earlier messages are not included. Replies use built-in explanations, not model-generated advice. Do not submit health records or other sensitive information.</p>
<h2 className="text-2xl font-serif">Analytics and session replay</h2><p>Optional analytics are off by default and require both verified configuration and your consent. The controls at the bottom of this page let you decline or withdraw consent. Where enabled, only approved usage events and broad public page categories are sent, not plan identifiers, notes, input values or full query strings. A small fixed set of referral categories (shared tool, embedded tool, Pinterest or YouTube) may also be counted after consent. Arbitrary campaign text and referrer addresses are not sent. With a separate opt-in, Microsoft Clarity collects masked session recordings and heatmaps on public pages. All page text and entered values are masked. Recording is stopped before navigation and remains off on account pages, saved or shared plans, search pages, and URLs containing query strings or fragments. Clarity may process public page addresses, device information and interaction patterns. Advertising storage is denied. You can withdraw consent using the controls below. Rejecting optional tracking does not prevent calculations or saving plans.</p>
<h2 className="text-2xl font-serif">External research-supplier links</h2><p>Product links may contain our public affiliate code and campaign source. We may earn a commission from qualifying purchases through those links. These fields identify our referral relationship, not you. We do not append calculator values, plan identifiers, notes, email addresses, directory search text or query strings from your visit. No supplier tracking script or external product image is loaded by this integration. Clicking a link opens the supplier site, whose own privacy and attribution policies then apply. A commission disclosure appears beside paid links.</p>
<h2 className="text-2xl font-serif">Product directory search</h2><p>The directory matches product names and formats locally in your browser. It does not send your search text to an AI provider or supplier, add it to a page URL, or save it as a product preference. It does not use health information, account details or saved calculation plans to rank products.</p>
<h2 className="text-2xl font-serif">Conversational research finder</h2><p>The research finder matches your questions to prepared research notes in your browser. Questions and replies are not sent to an AI service, our server or a supplier. They are not saved to an account, browser storage or the page address. The page keeps up to 12 exchanges while it is open. Leaving or reloading clears them. Session replay is disabled on this page. Do not enter personal health details or private lab information. Opening a cited study or product link sends an ordinary page request to that outside website.</p>
<h2 className="text-2xl font-serif">Service providers and retention</h2><p>Hosting, database, authentication, configured email delivery and optional AI services process the information needed for those functions. Saved records remain until deleted through supported controls or handled through a verified support request. Backup retention and any legally required retention need to be considered separately; this page does not promise immediate removal from every backup.</p>
<h2 className="text-2xl font-serif">Questions and requests</h2><p>Use the <Link className="underline" href="/contact">contact form</Link> to ask about access, correction or deletion. We may need to verify ownership before changing or disclosing account data. Do not send a password. The rights and retention obligations that apply can depend on your location and the circumstances.</p><Link className="underline" href="/">Back to BACwater.ai</Link></article>; }
