import Link from "next/link";
import { ResearchSupplierSection } from "@/components/partners/supplier-recommendations";
import { getSupplierCatalog, SUPPLIER_SOURCES } from "@/lib/partners/supplier-catalog";
import { Breadcrumbs } from "@/components/common/breadcrumbs";
export const metadata={title:"Research Supplies and BAC Water: Supplier Links",description:"Find BAC water and research product listings from the supplier. Read labels, lab reports, and how our supplier links work.",alternates:{canonical:"/recommendations"}};
export default function RecommendationsPage(){const products=getSupplierCatalog(),paid=products.some(p=>p.paid);return <div className="bac-supplies-page">
  <div className="mx-auto max-w-5xl px-4 sm:px-6 pt-9"><Breadcrumbs items={[{label:"Home",href:"/"},{label:"Research supplies",href:"/recommendations"}]}/><p className="eyebrow">Supplier links, not medical advice</p><h1 className="mt-3 text-3xl sm:text-5xl font-serif">Research supplies.<br/>Clear links. No guesswork.</h1><p className="mt-5 max-w-2xl leading-relaxed">The calculator comes first. These links are here when you want to read a supplier’s product label or lab report.</p><p className="mt-3 max-w-2xl text-sm">{paid?"Some links are paid links. We may earn a fee if you buy through them.":"These are ordinary supplier links. No paid referral link is active."} We have not tested these products.</p></div>
  <ResearchSupplierSection products={products}/>
  <div className="mx-auto max-w-3xl px-4 sm:px-6 pb-12 space-y-8"><section className="bac-info-card"><h2>What this list means</h2><p>Everyone sees the same list. Your numbers, notes, and account details do not pick the products. Nothing is added to a cart.</p><p>The supplier sells these items for lab research only. They are not for people or animals. A listing here does not mean a product is safe or right for your work.</p></section><section className="bac-info-card"><h2>Check before you buy</h2><p>Read the full name, label, and lab report for the exact batch. Check prices and stock on the supplier’s site. The supplier handles orders, shipping, returns, and product questions.</p><p>We do not display a price, discount, test score, or claim of approval. Supplier product names are not names for approved medicines.</p><p><a href={SUPPLIER_SOURCES.coa} rel="noopener noreferrer" referrerPolicy="no-referrer" className="underline">Supplier lab reports</a> · <a href={SUPPLIER_SOURCES.researchUse} rel="noopener noreferrer" referrerPolicy="no-referrer" className="underline">Research-use rules</a></p></section><section className="bac-info-card"><h2>How links work</h2><p>A product link opens a new tab on the supplier’s website. We do not add your entries or notes to it. The artwork is our own, not a photo of the product. No supplier script or product image loads on this site.</p><p>Paid links can turn on only after our account and the exact links are checked. Each paid link will say that we may earn a fee. A fee never changes the math.</p></section><p className="flex flex-wrap gap-4 text-sm"><Link href="/peptide-calculator" className="underline">Back to the calculator</Link><Link href="/privacy" className="underline">Privacy</Link><Link href="/editorial-policy" className="underline">How we check content</Link></p></div>
</div>;}
