import Link from "next/link";
import type { ReactNode } from "react";
function Figure({title,children,note="Illustrative arithmetic and notation only, not product instructions."}:{title:string;children:ReactNode;note?:string}) {
 return <figure className="my-7 rounded-2xl border border-[#c7d1bd] bg-[#f3f6ec] p-5 sm:p-7"><figcaption className="mb-4 text-xl font-serif text-[#18382d]">{title}</figcaption>{children}<p className="mt-4 text-sm leading-relaxed text-[#45604e]">{note}</p></figure>;
}
const card="rounded-xl border border-[#c7d1bd] bg-[#fffef9] p-4 text-base leading-relaxed";
export function GuideFigure({slug}:{slug:string}) {
 if(slug==="peptide-reconstitution-chart") return <Figure title="Printable concentration worksheet"><p>Print the worked arithmetic examples, then choose your product to check your own label values.</p><div className="mt-3 flex flex-wrap gap-4"><a className="min-h-11 inline-flex items-center underline" href="/learn/peptide-reconstitution-chart/chart.svg" target="_blank" rel="noopener noreferrer">Open the printable worksheet</a><Link className="min-h-11 inline-flex items-center underline" href="/tools/bac-water">Check your calculation</Link></div></Figure>;
 if(slug==="how-to-read-a-peptide-vial") return <Figure title="A fictitious label, three different quantities"><div className="grid gap-3 sm:grid-cols-3">{[["Total mass","12 mg","The amount of material."],["Final volume","4 mL","The total liquid volume."],["Concentration","3 mg/mL","Mass in each 1 mL: 12 ÷ 4."]].map(([label,value,copy])=><div className={card} key={label}><strong className="block text-sm">{label}</strong><p className="my-2 text-2xl font-semibold">{value}</p><p>{copy}</p></div>)}</div></Figure>;
 if(slug==="how-peptide-reconstitution-works") return <Figure title="Mass ÷ final volume = concentration"><p className="text-xl sm:text-2xl leading-relaxed font-semibold">12 mg ÷ 4 mL = 3 mg/mL</p><p className="mt-3">Start with the stated total mass and final volume. Neither value is chosen by the equation.</p><Link className="mt-3 inline-block underline" href="/methodology">Read the formula assumptions</Link></Figure>;
 if(slug==="how-to-read-an-insulin-syringe") return <Figure title="Count the spaces between labeled numbers" note="An abstract number line, not a drawing of a particular syringe. Check the actual device scale."><div className="grid grid-cols-6 border-b-2 border-[#18382d] pb-3 text-center font-semibold text-lg" role="img" aria-label="10, 12, 14, 16, 18, 20: five equal intervals, each worth two scale units.">{[10,12,14,16,18,20].map(n=><span className="border-l border-[#18382d]" key={n}>{n}</span>)}</div><p className="mt-4">(20 − 10) ÷ 5 intervals = <strong>2 scale units per interval</strong>.</p></Figure>;
 if(slug==="insulin-syringe-sizes") return <Figure title="Capacity is a volume label, not a tick size" note="These are capacity examples, not device recommendations. The marks on a particular device must be read separately."><div className="grid gap-3 sm:grid-cols-3">{["0.3 mL","0.5 mL","1 mL"].map(v=><div className={card} key={v}><strong className="text-2xl">{v}</strong><p className="mt-2">Capacity shown on a label</p><p className="mt-2 text-sm">Graduation spacing: check the device.</p></div>)}</div></Figure>;
 if(slug==="what-syringe-units-mean") return <Figure title="Volume conversion and mass calculation are separate"><ol className="grid gap-3 sm:grid-cols-2"><li className={card}><strong>1. U-100 units to volume</strong><p className="mt-2">25 ÷ 100 = 0.25 mL</p><p className="mt-2 text-sm">Requires a confirmed U-100 scale.</p><Link className="mt-3 inline-block underline" href="/tools/syringe-units">Use the U-100 converter</Link></li><li className={card}><strong>2. Volume to mass</strong><p className="mt-2">0.25 mL × 2 mg/mL = 0.5 mg</p><p className="mt-2 text-sm">Also requires the exact concentration.</p><Link className="mt-3 inline-block underline" href="/tools/dose">Use amount-to-volume</Link></li></ol></Figure>;
 if(slug==="too-much-bac-water") return <Figure title="Double the final volume, halve the concentration"><div className="grid gap-3 sm:grid-cols-2"><div className={card}><strong>Example A</strong><p>10 mg ÷ 2 mL = 5 mg/mL</p></div><div className={card}><strong>Example B</strong><p>10 mg ÷ 4 mL = 2.5 mg/mL</p></div></div><p className="mt-4">The idealized total mass is still 10 mg. This does not establish compatibility or permission to change the preparation.</p></Figure>;
 if(slug==="what-is-bac-water") return <Figure title="Read the complete product name" note="A terminology aid. Check the exact product label for formulation and permitted use."><dl className="grid gap-3 sm:grid-cols-2"><div className={card}><dt className="font-semibold">Bacteriostatic water</dt><dd className="mt-2">A finished water formulation with a preservative.</dd></div><div className={card}><dt className="font-semibold">Benzyl alcohol</dt><dd className="mt-2">An ingredient. Its name alone does not describe the finished formulation.</dd></div></dl></Figure>;
 if(slug==="how-to-store-reconstituted-peptides") return <Figure title="Keep these facts with your record" note="Copy instructions for the exact product. A calculator cannot fill in missing storage information."><ul className="list-disc space-y-2 pl-5">{["Exact formulation and container","Required temperature range and light protection","Opening or preparation date, if required","Any allowed time outside storage","Product-specific discard instructions and their source"].map(t=><li key={t}>{t}</li>)}</ul></Figure>;
 if(slug==="common-mistakes-to-avoid") return <Figure title="Wrong input → the check to make"><dl className="space-y-3">{[["mg entered as mcg","1 mg = 1,000 mcg. Convert the mass before calculating.","/tools/mg-to-mcg"],["Concentration entered as total mass","mg/mL is different from mg. Read the complete label.","/learn/how-to-read-a-peptide-vial"],["A previous product's result reused","Select the current product and recheck every amount and unit.","/peptide-calculator"]].map(([wrong,check,url])=><div className={card} key={wrong}><dt className="font-semibold">{wrong}</dt><dd className="mt-2">{check} <Link className="underline" href={url}>Open the relevant check</Link></dd></div>)}</dl></Figure>;
 return null;
}
