import assert from "node:assert/strict";
import { ownsPlan, storedRole, planWriteWhere, planCookieName } from "../security/authorization";
import { inlineMarkdown } from "../content/render";
const guest = { id: "db-id", publicId: "abcdefghij", userId: null, claimToken: "a".repeat(24) };
assert.equal(ownsPlan(guest, undefined, undefined), false);
assert.equal(ownsPlan(guest, "someone", "b".repeat(24)), false);
assert.equal(ownsPlan(guest, undefined, "a".repeat(24)), true);
assert.equal(ownsPlan({ ...guest, userId: "owner", claimToken: null }, "other", "a".repeat(24)), false);
assert.equal(ownsPlan({ ...guest, userId: "owner", claimToken: null }, "owner"), true);
assert.equal(ownsPlan({ ...guest, claimToken: null }, null, ""), false);
assert.equal(planCookieName("bad; Path=/"), null);
assert.deepEqual(planWriteWhere(guest), { id: "db-id", userId: null, claimToken: "a".repeat(24) });
assert.equal(storedRole(undefined), "user");
assert.equal(storedRole({ role: "admin" }), "admin");
assert.equal(storedRole({ role: "ADMIN" }), "user");
assert.equal(inlineMarkdown('<img src=x onerror="alert(1)">').includes("<img"), false);
assert.equal(inlineMarkdown('[bad](javascript:alert(1))').includes("href"), false);
assert.equal(inlineMarkdown('[bad](//evil.test)').includes("href"), false);
assert.ok(inlineMarkdown('[Read the guide](/learn/what-is-bac-water)').includes('href="/learn/what-is-bac-water"'));
assert.ok(inlineMarkdown('[Source](https://example.org/?a=1&b=2)').includes('a=1&amp;b=2'));
assert.equal(inlineMarkdown('**bold** and *italic*'), '<strong>bold</strong> and <em>italic</em>');
console.log("Audit authorization and safe-content fixtures passed.");
